### ISSUE TITLE
Can't access private theme repo even with personal access token

### ISSUE THREAD

**Issue by naneko** [afragen/git-updater#1000]
I created a personal access token with `read` and `read:packages` but the plugin is still reporting a 404 error when its trying to access my repo via the GitHub API. This is a regular non-enterprise user-owned (owned by this account) private repository. I've reset the cache multiple times and tried to see if I could get any hints to whats happening with Query Monitor but to no avail. I also turned on WP debug logging but I didn't see any error logs from Git Updater.

I currently have Bypass WP-Cron turned on in an attempt to work out what is happening but this issue seems to persist weather its on or off, after resetting the cache in both cases.

Does my repository need to have a release/tag? Can that release be marked as a pre-release?

My theme is listed under "installed plugins and themes" and I can confirm I have set the correct URI (`GitHub Theme URI: naneko/<repo>`)

That's all the info I have for the moment. Would appreciate any help 🙂

**Comment by afragen** [comment]
What is the primary branch called?

**Comment by naneko** [comment]
"main"

**Comment by afragen** [comment]
You must have the header `Primary Branch: main` set.

**Comment by naneko** [comment]
Ah I see. GitHub now makes the default branch "main" instead of "master" so maybe Git Updater should check for both and cache which one it finds? Anyway thanks!
