### ISSUE TITLE
Consider adding link to retrieve GitHub personal access token

### ISSUE THREAD

**Issue by jessuppi** [afragen/git-updater#1002]
Another item I thought might improve usability is adding a hyperlink directly in the Git Updater >> GitHub settings page for where users can generate a "personal access token" from their GitHub account:

https://git-updater.com/knowledge-base/settings/

As per the knowledge base, it would be generated at this URL: https://github.com/settings/tokens/new

Thanks again for all your contributions to this project.

**Comment by afragen** [comment]
I'll think about this. I was planning on bringing all the authentication into its own tab.

**Comment by jessuppi** [comment]
> I'll think about this. I was planning on bringing all the authentication into its own tab.

I think that would be a fantastic idea too, sort of "commodify" the various Git repo providers where they fit into your existing tabs and settings, rather than dedicating tabs/etc to each vendor per se.

Then a dedicated Authentication tab, kinda makes Git Updater the boss of things and more centralized.

Sort of like WooCommerce >> Payment Methods tab.

Another related adjustment might be having a dedicated tab for Installed Extensions (Plugins/Themes) where users can immediately see all recognized plugins and themes powered by Git Updater, regardless of which Git provider each extension is  hosting their source code at. (Just a quick thought, anyway, I don't know how it all fits together.)

**Comment by bugalwena** [comment]
@afragen, there's been several significant changes to my profile and business direction. First, my GitHub personal access token is in vs. code not used. I'm a bit confused. 

I had time off. Before my break, I copied the GitHub access token and pasted it into vs. code twice, but I got another message I needed a GitHub access token for an extension. Like before. 


The vs. studio code is working, with no issues except for requests for GitHub access tokens. 

I've had significant headaches updating my ID to bugal Wena Close; I have a new email address but still using my ACL business email account. My GitHub phone number has been disabled since my time away. 

I tried to contact GitHub support a couple of weeks ago but never heard back. I must have got it wrong. But need the GitHub access token for an extension. 

Thanks

**Comment by afragen** [comment]
I'm having a hard time figuring out your specific issue.

I don't understand what you mean when you say 

> I copied the GitHub access token and pasted it into vs. code twice, but I got another message I needed a GitHub access token for an extension.

**Comment by jessuppi** [comment]
I think @bugalwena is talking about an unrelated situation where he pasted in his GitHub token to GU but then later forgot what the token was, and is now trying to ask GitHub for help... I don't think they can help you with that.

You can simply cancel the other  token or wait for it to expire, and/or generate a new token and use that instead.

Might want to discuss this on the GU Slack instead of GitHub Issues though?

**Comment by afragen** [comment]
@jessuppi a fresh perspective is always good.

There are icons denoting errors (API not connecting) in the respective tabs. There is no way for a _version conflict_ to be identified.

The primary access token field is labeled as such and any field associated with a specific plugin/theme is a private repo key.

I'm also in the midst of combining all the authentication into a single tab.

**Comment by jessuppi** [comment]
Makes sense, I guess every single private repo would need its own private key, which presents issues when trying to simplify the settings page layout too much.

I do still think it might help usability to be able to see all "recognized" Git-powered extensions in one place maybe. On the default Plugins page, I believe Git Updater adds a GitHub icon to the plugins it recognizes, but there's no way to do that with themes due to the kinda janky layout WordPress Core uses for Themes.

Ultimately however, this might be more of a complaint with WordPress Core layout though.

**Comment by afragen** [comment]
If you are the owner of the private repo it doesn't require a separate key. Only if you wanted to create another key to share with someone else that you didn't give access to the repo directly.

if you open the theme card you will see a similar git icon.
