### ISSUE TITLE
PHP Warning:  Undefined variable $asset in /var/www/html/wp-content/plugins/git-updater/src/Git_Updater/Traits/API_Common.php on line 71

### ISSUE THREAD

**Issue by jessuppi** [afragen/git-updater#1003]
Sorry for the multiple Issues, I will take a break after this. I saw this error in the log:

    PHP Warning:  Undefined variable $asset in /var/www/html/wp-content/plugins/git-updater/src/Git_Updater/Traits/API_Common.php on line 71

I'm having trouble updating a theme using Releases only (not the Master/Main branch, which is not production ready) and I thought perhaps this error might be related, or maybe not.

Our theme is using the `Release Asset: true` header already, but anyway I don't want to knock this off-topic.

**Comment by afragen** [comment]
It is related. Does the API have a complete response for the repo?

**Comment by jessuppi** [comment]
By the way, this theme is in a public GitHub repo. I tried generating a personal token and input to Git Updater settings just in case there was some limitation, but it doesn't seem to have made a difference.

**Comment by afragen** [comment]
What's the repo URI?

**Comment by jessuppi** [comment]
https://github.com/littlebizzy/hovercraft

I made a few "test" release versions 0.0.1 and 0.0.2 but they are not recognized by Git Updater, even after 24 hours, but Git Updater plugin itself updates correctly so the crons seem to be working.

**Comment by afragen** [comment]
With this theme you have a problem. Once you start tagging you must continue tagging. Your most recent tag in 0.0.2 which has a version header of 0.0.1. Current `master` is 0.0.3. Need to tighten that all up.

To test updates I usually just decrease the local version number.

**Comment by jessuppi** [comment]
Hmm, my understand of the documentation is that when using `Release Asset: true` Git Updater will ignore master/etc branches and only look at tagged releases?

So if I have the package 0.0.1 installed on a WordPress site, then later I tag 0.0.2, shouldn't Git Updater see the new release and pull an update from GitHub regardless of whatever the master/etc branches are doing?

**Comment by afragen** [comment]
But Git Updater looks to the designated branch to check the version header. When tagging or using release assets, Git Updater uses those for download links.

If you don't keep control of your versions bad things will happen, ie, it won't work.

**Comment by jessuppi** [comment]
> But Git Updater looks to the designated branch to check the version header. When tagging or using release assets, Git Updater uses those for download links.
> 
> If you don't keep control of your versions bad things will happen, ie, it won't work.

I'm sorry but I don't understand. According to the docs, using `Release Asset: true` makes Git Updater look for new releases via the tags instead of via the branches. So why is it looking at the Master branch at all? It shouldn't be.

Even if it was looking at the Master branch, that is 0.0.3 in the `style.css` so it should still recognize a new version on the Master branch vs. the tagged releases (0.0.1 and 0.0.2 are tagged).

When you say it "looks... at the version header" which exact files are you talking about?

**Comment by afragen** [comment]
For themes, GU looks at the installed style.css for headers. It then looks to the API and the remote repository for a version check of the current version for the specified branch. 

Tagging and using release assets just allows GU it use your designated download for updates.

**Comment by afragen** [comment]
FYI you are **tagging** releases but you are **not** using release assets. 

A release asset is usually plugin or theme that requires a build process. The results of that build process are then uploaded to the release in a zip file as a release asset.

**Comment by jessuppi** [comment]
Very interestingly, earlier today I changed the `style.css` version in the Master branch to 0.0.4, added a few files, and then tagged a new release 0.0.4 and didn't touch anything in the Git Updater, I just waited. And sure enough several hours later it's now showing a theme update is available under `/wp-admin/update-core.php` ... 

The "update" option is missing from the actual theme profile page, however... although a red "update available" dot does exist on the Themes menu link in the WP Admin sidebar. The "Enable auto-updates" link is also missing from the theme profile page too but I'm not sure that is supported by Git Updater for themes.

I don't know why it worked today, but a few days ago it wouldn't work... I did the same exact thing.

When I tried to update, however, there was a new error:

    An error occurred while updating hovercraft: Update package not available.

And on the update prompt itself, it says **You have version installed. Update to 0.0.4** ... missing the current version installed, despite current installed theme having proper versioning 0.0.3 in `style.css`. So there seems to be various issues going on and I'm not sure if they are all related or not.

> For themes, GU looks at the installed style.css for headers. It then looks to the API and the remote repository for a version check of the current version for the specified branch.
> 
> Tagging and using release assets just allows GU it use your designated download for updates.

So, the Master branch `style.css` is the key file here it sounds like, meaning that the Master branch (or other specified) is still going to be the deciding factor whether Git Updater pulls an update or not. For agencies or repos that don't use Master for production-ready code, I don't think this behavior is desirable for `Release Asset: true` and/or, I fail to understand the purpose of this header if it still relies on Master branch telling it when to trigger.

I don't know if you'd consider it, but I would like to propose changes to this behavior in a new Issue...

Back to the original error on this Issue, it sounds like it was just failing to parse the repo properly initially, although after a few days and a few tries, I guess it worked, but not completely.

**Comment by jessuppi** [comment]
Screenshots of what I'm talking about:

![Screenshot 2022-09-30 16 57 43](https://user-images.githubusercontent.com/17551083/193245766-1425f4af-1597-449c-bd31-cc4f1c4a26e1.png)
![Screenshot 2022-09-30 16 57 26](https://user-images.githubusercontent.com/17551083/193245778-e91a80d3-7283-41b5-b924-cbfe087c0558.png)

**Comment by afragen** [comment]
Your repo does not use release assets. Please remove that header as it is the cause of the problem.

If you use a primary branch other than `master` it must be designated in a header as `Primary Branch`. 

https://git-updater.com/knowledge-base/required-headers/ has info about these headers.

**Comment by afragen** [comment]
> So, the Master branch style.css is the key file here it sounds like, meaning that the Master branch (or other specified) is still going to be the deciding factor whether Git Updater pulls an update or not. 

The primary branch `style.css` file at the root level of the repository is where Git Updater gets API data for version checking.

> For agencies or repos that don't use Master for production-ready code, I don't think this behavior is desirable for Release Asset: true and/or, I fail to understand the purpose of this header if it still relies on Master branch telling it when to trigger.

If the repository requires a build step, that output needs to be zipped and added to the release as a release asset. The `Release Asset` header tells Git Updater not to use the code from the branch for downloading but to use the asset added to the release.

For your theme. remove the `Release Asset` header both locally and remotely.

**Comment by afragen** [comment]
> When you say it "looks... at the version header" which exact files are you talking about?

https://github.com/littlebizzy/hovercraft/blob/master/style.css

**Comment by jessuppi** [comment]
> For your theme. remove the `Release Asset` header both locally and remotely.

Just an update that I've been testing this the past few days, and you're suggested fix did work. Removing the `Release Asset` header locally and in our repo Master branch allowed updates to be detected and installed reliably. 

However, even if we didn't tag a release, Git Updater thinks a new version is available if Master `style.css` has a newer version in the file which is not desirable for us, so I'll open a new Issue, thanks again.

**Comment by afragen** [comment]
Git Updater checks the remote version and compares that to the local version to determine if an update is available. I might suggest using a git flow development style.
