### ISSUE TITLE
Fatal Error GU_Trait

### ISSUE THREAD

**Issue by ploplu** [afragen/git-updater#1004]
Hi,
I regularly get  this error. It's quite annoying ;)
AH01071: Got error 'PHP message: PHP Fatal error: Trait 'Fragen\|Git_ Updater\\Traits\\GU_Trait' not found in /var/www/vhosts/---/wp-content/plugins/git-updater-pro/src/Git_Updater_PRO/Bootstra p.php on line 27', referer: https://----.lu/

any clue ?

**Comment by afragen** [comment]
Do you have the core Git Updater plugin installed?

**Comment by ploplu** [comment]
![image](https://user-images.githubusercontent.com/47015058/193246705-76ce98f0-ef05-4eec-bb06-f8fa44a02c03.png)

**Comment by afragen** [comment]
I'm closing this as the next major release fixes this as everything will again be part of the main plugin. The Git Updater PRO plugin will be deprecated as it will be included.
