### ISSUE TITLE
PHP Fatal error:  Call to undefined method Appsero\Insights::add_plugin_data()

### ISSUE THREAD

**Issue by janboddez** [afragen/git-updater#1006]
Latest update introduces, at least on my setup, a fatal error: 
```
PHP Fatal error:  Uncaught Error: Call to undefined method Appsero\Insights::add_plugin_data() in <...>/wp-content/plugins/git-updater/src/Git_Updater/GU_Appsero.php:64
```

**Comment by afragen** [comment]
Should be fixed in v11.1.4

**Comment by afragen** [comment]
If can't update due to fatal comment out the following line then update.

https://github.com/afragen/git-updater/blob/1f4a2978ed937af2f033400103f1d50eaf679d16/git-updater.php#L53

**Comment by janboddez** [comment]
It happens with 11.1.4 but only on this one site. I think it may be a conflict with the WPGraphQL plugin, which also loads the Appsero dependency, but a different version that does not come with the `Insights::add_plugin_data()` method.

**Comment by janboddez** [comment]
(Hmm, can't we opt out of Appsero tracking?)

**Comment by afragen** [comment]
I just updated to remove that SDK option. It's clearly an issue when others using the SDK don't keep it up to date. The SDK was last updated August 23, 2022

**Comment by janboddez** [comment]
I've had some luck with https://github.com/humbug/php-scoper to avoid conflicts like these but understood it's really more of a WordPress limitation. (No proper, Composer or otherwise, dependency management.)

**Comment by afragen** [comment]
I use composer and always try to run a `composer update` before a release. unfortunately others don't do the same.

**Comment by afragen** [comment]
I have notified WPGraphQL of this too.
