### ISSUE TITLE
Consider option to use tagged releases instead of Master style.css

### ISSUE THREAD

**Issue by jessuppi** [afragen/git-updater#1007]
This is a follow up to: https://github.com/afragen/git-updater/issues/1003

I had misunderstood the purpose of the `Release Asset` header, which was causing issues with detecting and installing new versions of our WordPress theme via the GitHub repo.

Based on that discussion I wished to propose that Git Updater consider a new option to disable using `style.css` from the Master (Main) branch of repos for the purposes of detecting new versions of plugins or themes. 

I know that traditionally, Git repos use Master/Main for bleeding edge releases and other branches for development work, which are then merged back into Master/Main. However these days, agencies use GitHub in many different ways, and in our case to keep things simple esp. for smaller projects, we don't follow the traditional workflow, and simply use Master/Main for dev work and then tag a new release whenever it's ready for downloading or deployment, etc.

For example, right now our test theme https://github.com/littlebizzy/hovercraft ... has version `0.0.7` on the `style.css` file in Master, but there is no tagged release yet for version `0.0.7` and yet Git Updater is telling WP Admin a new version is available.

Would you consider adding support for a new header, perhaps e.g. `Tagged Releases: true` or something like that to only look for new versions in tagged releases?

On a side note, I'm not an expert about building releases with assets, but it might help to use the plural `Release Assets` instead of the singular `Release Asset` for better clarity: https://docs.github.com/en/rest/releases/assets

**Comment by jessuppi** [comment]
Update: I went ahead and "updated" the installed theme per Git Updater "new version" notice, but after updating, it's still using the older theme version `0.0.6` I guess because Git Updater pulled the latest tagged release ZIP (being `0.0.6`).

So this is potentially a bigger conflict than I had first believed.

**Comment by afragen** [comment]
https://git-updater.com/knowledge-base/required-headers/

**Comment by afragen** [comment]
There is no API to look inside a tagged release to determine its version number. He file name can and will be inaccurate.

**Comment by afragen** [comment]
https://git-updater.com/knowledge-base/versions-branches/

**Comment by jessuppi** [comment]
@afragen I'm not sure if a basic `curl` solution might work?

https://stackoverflow.com/questions/29109673/is-there-a-way-to-get-the-latest-tag-of-a-given-repo-using-github-api-v3

    curl https://api.github.com/repos/$org/$repo/releases/latest -s | jq .name -r

Or allternatively:

    curl  "https://api.github.com/repos/certbot/certbot/tags" | jq -r '.[0].name'

There is an older solution on that page too using the GitHub Tags API, also a newer solution using GraphQL API (v4) that sorts tagged releases via commit date which could also alleviate concerns re: version naming/syntax.

There could be other concerns with such an approach, I'm not sure, but if it's opt-in via headers I think it might be a welcome addition for teams like mine who are not Git/branch fanatics!

**Comment by afragen** [comment]
The problem here is that the latest tag can be named anything. It doesn't have to conform to a specific pattern. FWIW, I already query the API for all the tags and all the latest release.

I'm sorry but I have been using the current pattern for many years and it has proven to be extremely versatile. In this case the difference is how you and your team utilize GitHub.

If you find it easier to commit to a single branch, that's fine. Just don't update the version number until you are prepared to tag a release.

**Comment by jessuppi** [comment]
> The problem here is that the latest tag can be named anything.

I don't think this is a problem, it seems like a user-friendly benefit. I see several other users of GitHub Updater having problems only to discover there is a naming conflict in their versions, as it's erroneously ignoring new releases.

The current model actively prevents e.g. `alpha-` or `beta-` etc version evolution.

> I'm sorry but I have been using the current pattern for many years and it has proven to be extremely versatile. In this case the difference is how you and your team utilize GitHub.

What I'm proposing isn't a change from default functionality per se, it would be an opt-in feature using a header. And it could also introduce more teams to using GitHub, as I recall learning how branches work was the most confusing part of GitHub for me several years ago... only to discover, you don't need to use them at all.

> If you find it easier to commit to a single branch, that's fine. Just don't update the version number until you are prepared to tag a release.

This puts the risk of conflict on otherwise common user behavior though, instead of actively avoiding it. If an agency is not using separate branches for dev work, there is no reason to expect `style.css` to only be updated right before tagging. And it shifts the learning curve away from "GitHub basics" and onto somewhat exclusive Git Updater intricacies.

**Comment by afragen** [comment]
> The current model actively prevents e.g. alpha- or beta- etc version evolution.

This is inaccurate. Git Updater uses PHP's `version_compare()` and this does allow for all [semantic versioning](https://semver.org).

Fundamentally, Git Updater compares the local and remote number in the `Version` header using `version_compare()`. If a higher version is located remotely then an update is registered.

What specifically are you trying to accomplish with Git Updater? 
Are you looking to update against any (version change / any commit / any tagged release)?

You don't need to tag releases. If you do, the latest tagged release will always be used for the download link. If you update the remote version number and don't correspondingly issue a new tagged release, you will see an update showing but it will update using the tag. This is all described in https://git-updater.com/knowledge-base/versions-branches/

**Comment by jessuppi** [comment]
@afragen PHP has serious limitations though with comparing versions. I would argue the only "guaranteed" way to know which tagged release is the latest version is to check timestamps using methods mentioned above. Obviously those solutions are GitHub specific, and might not work with other hosted Git providers like GitLab, though...

And the usability benefits are significant... less researching Git Updater documentation, less testing and learning for new users... just install your plugin, add the headers, and it works after that.

> Are you looking to update against any (version change / any commit / any tagged release)?

Yes, possibly. Teams could worry less about tags:
- `alpha-test1`
- `beta-design-v2`
- `0.0.1`
- `v1.0.4` 
- etc

Currently Git Updater is restricting their release decisions, instead of complimenting potential naming improvements. For example, teams who are bad at semantic versioning but get better at it over time, etc. Or teams who simply suck at using GitHub and don't understand branching (in my experience, this is many of them).

> What specifically are you trying to accomplish with Git Updater?

Ultimately I'd like to integrate Git Updater into our [SlickStack](https://github.com/littlebizzy/slickstack) project and help more newbies start using cloud servers and GitHub, empowering them to think more in terms of the open web and less about vendors.

Yours is the best Git integration so far, I think huge potential to empower less tech-savvy teams.

**Comment by afragen** [comment]
@jessuppi I appreciate that you like and use Git Updater. 

Git Updater functions in a specific manner and I don't have any intention of changing how it functions to suit your team's workflow. I might suggest that your team consider learning to work with the plugin. These parameters have been in place for well over 5 yrs. If your team is unable to function within the plugin's parameters you may need to find an alternate solution.
