### ISSUE TITLE
gu_get_remote_plugin cron job stale

### ISSUE THREAD

**Issue by pcoweb** [afragen/git-updater#1009]
the cron job 'gu_get_remote_plugin' is stale as reported by  WP Crontrol. It was due 3 months and 1 week ago. Is it safe to remove this using the wp cli command
wp cron event delete gu_get_remote_plugin

My cron report tells me it is running each time the cron runs, but it is never deleted from the scheduled list.

**Comment by afragen** [comment]
If you have WP-CLI might as well run `wp cron event run --due-now`

**Comment by pcoweb** [comment]
Thanks so much. It seems to be stuck in the scheduled list. I tried 'due-now' and also 'delete'. When I look at the list, it is still there. Suggestions?
```
    [dp-760c576419]$ wp cron event run --due-now
    Executed the cron event 'gu_get_remote_plugin' in 0.003s.
    Executed the cron event 'action_scheduler_run_queue' in 0.013s.
    Success: Executed a total of 2 cron events.
    [dp-760c576419]$ wp cron event delete gu_get_remote_plugin
    Success: Deleted the cron event 'gu_get_remote_plugin'.
    [dp-760c576419]$ wp cron event list
    +------------------------------------------+---------------------+-----------------------+---------------+
    | hook                                     | next_run_gmt        | next_run_relative     | recurrence    |
    +------------------------------------------+---------------------+-----------------------+---------------+
    | gu_get_remote_plugin                     | 2022-07-10 23:49:21 | now                   | Non-repeating |
    | action_scheduler_run_queue               | 2022-10-19 19:20:55 | 33 seconds            | 1 minute      |
    | jetpack_display_posts_widget_cron_update | 2022-10-19 19:23:03 | 2 minutes 41 seconds  | 10 minutes    |
    | jetpack_sync_full_cron                   | 2022-10-19 19:23:05 | 2 minutes 43 seconds  | 5 minutes     |
```

**Comment by pcoweb** [comment]
My host provider edited the cron table directly to delete the hook.

**Comment by afragen** [comment]
Very strange. This cron task is created approximately twice daily to refresh the API data for the plugins/themes. Was there any issue in the Git Updater Settings you were notified of?
