### ISSUE TITLE
404 for JS file - points at theme rather than plugin

### ISSUE THREAD

**Issue by praggmatica** [afragen/git-updater#1012]
Hi! I've updated to the latest version (11.1.8), and my wp-admin console and error logs are being bogged down by the following link throwing a 404 error:

https://example.com/wp-content/themes/example/vendor/afragen/wp-dismiss-notice/js/dismiss-notice.js?ver=6.0.3

I searched for it in my files, and found that the "afragen" reference is in this plugin. Looks like it's not pointing at the right path (going for the theme folder rather than the plugins folder).

Can you fix this? Thanks!

**Comment by afragen** [comment]
Sure looks like that's coming from the theme and not this plugin.

**Comment by afragen** [comment]
The code should be looking https://github.com/afragen/git-updater/blob/develop/vendor/afragen/wp-dismiss-notice/wp-dismiss-notice.php#L37-L57 to determine the correct URL.

I've not seen an issue with this in Git Updater. Is it possible the `afragen/wp-dependency-installer` is being used elsewhere?

**Comment by afragen** [comment]
Can you share a list of active plugins and theme?

Also, that code has a transient set for a week.

**Comment by afragen** [comment]
Is there any way you could let me know what the variables in the above link code produce?

**Comment by afragen** [comment]
Specifically, what URL does this code produce. 

```php
$plugin_js_url    = plugins_url( 'js/dismiss-notice.js', __FILE__, 'wp-dismiss-notice' );
```

What happens when you go to the URL in your browser?

**Comment by 24Degrees** [comment]
Hi all,
I just performed a clean install (even Windows) and I'm using mamp pro for theme dev. I also just got this error while trying out this plugin. My exact error log is:

`ps://24degrees/wp-content/themes/artem/vendor/afragen/wp-dismiss-notice/js/dismiss-notice.js?ver=6.2 net::ERR_ABORTED 404 (Not Found)`

And I don't know if this is related but I haven't seen a "theme needs update" message yet although I already updated the style.css version form 0.1.0 to 0.1.1. But maybe the plugin works in a different way, I'm still learning.

**Comment by 24Degrees** [comment]
Oh I forgot: default Wordpress installation, clean, no Multisite yet. List of plugins: Akismet Anti-Sppam, Debug This, Git Updater, Hello dolly, Instant Images and Query Monitor.
Hope this helps.

**Comment by afragen** [comment]
Is this still happening in Git Updater v12.2.1?

**Comment by 24Degrees** [comment]
Hello afragen,

I checked and unfortunately the answer is yes: Version 12.2.1 | By Andy Fragen

But to be honest: inm my testenv in MAMP Pro, the error is gone now, I have no idea what I did or what happened. So the plugin is still active but the error is gone.  I will install the plugin on my live multisite server now and let you know what happened.

**Comment by praggmatica** [comment]
Hi -

I originally opened this issue back in 2022. I've tested the latest version on my website that was having a problem, and I no longer see the problem with the theme and plugins present.

Looks like the person who commented on this also is seeing it gone. 

I'll close this out, my issue is resolved. Thanks.
