### ISSUE TITLE
Failed updating Git Updater Pro plugin

### ISSUE THREAD

**Issue by MSERobert** [afragen/git-updater#1013]
Hello,

Not sure if this belongs here but I am having a problem upgrading Pro from 2.0.1 to 2.1.1. It tells me "Download failed. Unauthorized".
The plugin is activated and shows 7 months left in the license.

Thanks.

**Comment by afragen** [comment]
Hmm, and this is with 2.1.1.  Sorry, I'll fix. I'll ping back here.

**Comment by afragen** [comment]
Update to latest Git Updater, now at v11.1.9. That should solve the issue.

**Comment by MSERobert** [comment]
Yes, that did the trick. Thanks.
