### ISSUE TITLE
Bitbucket icon display

### ISSUE THREAD

**Issue by jbleys** [afragen/git-updater#1016]
Hi,

Is the icon on the Bitbucket tab supposed to be displayed like this?

![image](https://user-images.githubusercontent.com/2615272/205761235-cb1329ca-2063-437e-b3ae-25308d8e8acf.png)

Plugin: git-updater-bitbucket
Version: 2.0.1

Kind regards,
Jasper

**Comment by afragen** [comment]
In next `develop` branch release and next release it will be hidden.

My plan is to use the icon (smaller) as an oAuth link.
