### ISSUE TITLE
No way to add tokens?

### ISSUE THREAD

**Issue by bjvogt** [afragen/git-updater#1018]
I'm trying to use git updater to access some private repos.  I have had an older version installed on my multisite network for some time, but it stopped working.  

I've deleted the old plugin folder, and downloaded the v. 12.0.0 Zip file.  I've done this via the Git repo master branch as well as the links to download on git-updater.com.  

Regardless of workflow, two consistent problems occur.  First, on the Plugins page, a warning tells me I'm in the Devel tree.  I am not.  I've triple checked and reinstalled three times from the master tree zip file.  

Second, under the Github tab, I do see a list of several repos.  All have the red circle/exclamation point.  None offer a field for adding a token.  There used to be a place on that screen, above the list of repos, for a single token.  That is also missing.  

I'm wondering if perhaps some detritus in the database from the older version (11.1 or so) might be causing problems?  

Thanks for any help.  I tried to get to the Slack channel, but the Request an Invite link threw a 404 and trying to login to Slack also failed.  So, hope this is ok here.  

Cheers,
b

**Comment by afragen** [comment]
Can you share a screenshot?

**Comment by bjvogt** [comment]
I've tried to install from these two zip archives:
https://git-updater.com/wp-content/uploads/2022/12/git-updater-12.0.0.zip
https://github.com/afragen/git-updater/archive/refs/heads/master.zip

From the network plugins page: 

![Screen Shot 2022-12-13 at 2 37 24 PM](https://user-images.githubusercontent.com/2007651/207460244-22998a77-981f-4b05-ac70-abff36eff288.png)

From the Github Settings tab:  
(Most of these should be public, but the UW Storytelling Modules is not.)

![Screen Shot 2022-12-13 at 2 55 38 PM](https://user-images.githubusercontent.com/2007651/207462875-3be300cf-fbd5-4878-9b6d-c0bfdbde9621.png)

Thanks!

**Comment by afragen** [comment]
Use the branch switching to switch to the tag or master. 

I don't know why you. Don't see the area to enter an access token. Trying clearing caches in browser, etc.

**Comment by bjvogt** [comment]
I have enabled branch switching: 
<img width="709" alt="Screen Shot 2022-12-14 at 9 28 02 AM" src="https://user-images.githubusercontent.com/2007651/207665737-1ffaf2dd-61f5-43c7-a6b6-a4f2d71dacff.png">

But there's no where to indicate which branch to pull from: 
<img width="1101" alt="Screen Shot 2022-12-14 at 9 29 07 AM" src="https://user-images.githubusercontent.com/2007651/207665824-1f358074-9afe-42ac-b21d-1e085c07004d.png">

No changes to the git updater github settings tab: 
<img width="712" alt="Screen Shot 2022-12-14 at 9 30 17 AM" src="https://user-images.githubusercontent.com/2007651/207665975-da88f604-ee8f-4e0b-8956-907ac3901aa1.png">

I've tried on several different machines/browsers as well, so cache should not be the issue.  

Prior to the 12.0.0 release, I did try to update my older version that had stopped working.  I deleted the folder then uploaded the 11.?.? release.  Even before it was activated, that plugin directory caused my whole multisite network to crash with a PHP error.  Glad to see 12.0.0 doesn't do that but ... perhaps a clue?

Thanks!

**Comment by afragen** [comment]
I don't know what's going on. Can you share the list of active plugins?

You might try deleting all Git Updater related plugins and then re-install from https://git-updater.com

**Comment by afragen** [comment]
Also, check the Bypass WP-Cron in Settings.

https://git-updater.com/knowledge-base/troubleshooting/

**Comment by bjvogt** [comment]
This is on a multisite network -- I can provide the list of ~100 plugins we use across 70-odd sites, but only a handful are network activated.  Want the whole list?  

The only git updater plugin I've installed is git updater itself and it has been fully deleted from the filesystem several times.  The WP database, though, may have old details or structure.   This feels like what I've seen happen with other plugins in the past, when perhaps a missed update included a db structure tweak, that never occurred because of the missed update, leading to a mismatch in what the code expects and what resides in the db.  

I'll go try bypassing wp-cron.  

thanks again for your time!

**Comment by bjvogt** [comment]
Hey how about that!  bypassing wp-cron definitely a difference maker!  
<img width="788" alt="Screen Shot 2022-12-15 at 12 33 33 PM" src="https://user-images.githubusercontent.com/2007651/207961405-8ac4dfdc-df5e-4353-8b27-5253931b7164.png">

I will generate a new token and hope I can come back to close this thread!

**Comment by bjvogt** [comment]
Well, closer.  I generated a token with everything checked, just in case the token itself was the obstacle.  

I'm able to enter a token, and I see per-repo token fields, so much better!  I even see git updated and enable media replace as working.  But no joy on any of our institutional repos, public (UW WordPress Theme) or not (UW Storytelling Modules).

Registering my token did remove the API rate limiting error, so I'm inclined to think the token itself is OK.

<img width="781" alt="Screen Shot 2022-12-15 at 12 53 53 PM" src="https://user-images.githubusercontent.com/2007651/207965386-d6951919-eb3a-4c01-b4ba-019bc4cd8d77.png">

**Comment by afragen** [comment]
Does your user own the repositories? Does your user have read access to the repositories?

If you install Query Monitor you should be able to see what the HTTP errors are. A 401 is an authentication issue.

**Comment by bjvogt** [comment]
Indeed!  We had a username mismatch years in the making.  Wow!  I wonder how we'd have found it if not for this issue.

Thanks very much for your help!

<img width="355" alt="Screen Shot 2022-12-15 at 3 58 31 PM" src="https://user-images.githubusercontent.com/2007651/207991551-6f18f47c-67ef-4ffa-a167-fbcebfda2620.png">
