### ISSUE TITLE
Continued issues with WordPress.org conflicting with updates

### ISSUE THREAD

**Issue by jessuppi** [afragen/git-updater#1019]
After testing the "official" Git Updater filter snippet for the past few days that is meant to prevent WordPress.org from conflicting with specific plugins or themes being updated via GitHub (if the same directory namespace exists), it looks like there are possibly ongoing problems with this working properly.

Ref: https://git-updater.com/knowledge-base/wordpress-org-directory/

```
add_filter( 'gu_override_dot_org', function() {
    return [ 
        'the-events-calendar-category-colors/the-events-calendar-category-colors.php', //plugin format
        'my-popular-theme' // theme slug
    ];
});
```

I have this snippet on 2 different plugins for testing purposes. On the first plugin, a conflicting plugin does not yet exist on WordPress.org but I expected it might in the future. On that plugin, I see this (correct) message in Git Updater:

> The following plugins or themes might exist on wp.org, but any updates will be downloaded from their respective git repositories.

However, on the second plugin, there is already a conflicting plugin on WordPress.org. On this plugin, the above message does not exist and on the "GitHub" tab in Git Updater settings, a tooltip also exists which states:

> This repository is hosted on WordPress.org.

Anyway, I tested a patch by changing to this snippet instead:

```
add_filter( 'override_dot_org', function() {
    return [ 
        'plugin-folder/plugin-script.php'
    ];
});
```

I then removed the `gu_` prefix from both [this line](https://github.com/afragen/git-updater/blob/develop/src/Git_Updater/Plugin.php#L455) and [this line](https://github.com/afragen/git-updater/blob/develop/src/Git_Updater/Traits/GU_Trait.php#L284) and cleared all caches, released a new version of my test plugin on GitHub, and sure enough it's now working properly with Git Updater. I'm pretty bad at PHP, esp. classes, but I believe this is due to a spelling conflict with `public function override_dot_org( $type, $repo ) { ...`

However, I'm guessing you'd probably want to patch this the opposite way, by adding the missing `gu_` prefix to the class name if in fact this is a bug, so I didn't submit a PR.

Related issues:

https://github.com/afragen/git-updater/issues/746
https://github.com/afragen/git-updater/issues/581
https://github.com/afragen/git-updater/issues/893
https://github.com/afragen/git-updater/issues/876

**Comment by afragen** [comment]
Can you provide the exact filter and plugin combination that you state does NOT work?

**Comment by afragen** [comment]
If there are other plugins making use of this feature, like bph/gutenberg, it's possible you're running into a conflict with the return value.

In bph/gutenberg the filter is as follows,

```php
add_filter(
	'gu_override_dot_org',
	function ( $overrides ) {
		return array_merge(
			$overrides,
			array( 'gutenberg/gutenberg.php' )
		);
	}
);
```

I know this one works. I'll update the KB article with this usage.

**Comment by jessuppi** [comment]
Here is the plugin that does NOT work: https://github.com/littlebizzy/contact-details

Note: there is currently a conflicting plugin on WordPress.org.

```
// disable wordpress.org updates
add_filter( 'gu_override_dot_org', function() {
    return [ 
        'contact-details/contact-details.php'
    ];
});
```

Here is the plugin that does work: https://github.com/littlebizzy/statcounter

Note: there is not yet any conflicting plugin on WordPress.org.

```
// disable wordpress.org updates
add_filter( 'gu_override_dot_org', function() {
    return [ 
        'statcounter/statcounter.php'
    ];
});
```

Anyway maybe you're right that it's caused by testing both these plugins on the same website... I will try your new snippet and share what the results are.

**Comment by jessuppi** [comment]
Woohoo! Your new snippet looks to function properly.

I replaced both snippets in the 2 plugins, reinstalled Git Updater, cleared all caches, refreshed a few times and now both of the plugins are recognized properly under **Overridden Plugins and Themes** and the GitHub tab also.

And, the pending update is accurate now (via GitHub) instead of WordPress.org.

**Comment by jessuppi** [comment]
This simple version also works well for our LittleBizzy plugins:

https://slickstack.io/forum/topic/override-wordpress-org-namespace-conflicts-with-git-updater

```
// Disable WordPress.org updates for this plugin
add_filter( 'gu_override_dot_org', function( $overrides ) {
    $overrides[] = 'seo-genius/seo-genius.php';
    return $overrides;
}, 999 );
```
