### ISSUE TITLE
New upgrade nag is quite annoying

### ISSUE THREAD

**Issue by chesio** [afragen/git-updater#1020]
Hi Andy,

I appreciate your work on Git Updater, but I'm always really disappointed when a free plugin suddenly starts rendering an upgrade nag that is impossible to dismiss permanently as in case of Git Updater in version 12.

Would you consider changing the behaviour and make the nag permanently dismissible?

**Comment by chesio** [comment]
I now noticed that the nag can be permanently dismissed from some admin pages (like dashboard), but not from plugins page. Ideally, it should be enough to dismiss the nag once for all admin pages.

**Comment by afragen** [comment]
@chesio the notice is dismissible for 5 days. I can certainly consider increasing the timeout. 

The simplest way to dismiss it permanently is to purchase a license.😉. I believe I've made the license very reasonable.

**Comment by chesio** [comment]
@afragen Thanks for prompt reaction!

5 days timeout would be fine, but somehow on plugins page it is really permanent - even if I dismiss it, it's there next time I visit the page. On some other admin pages, where it's also shown, I can dismiss it, but I have to do it on every such page individually.

Since the version 12 is out for some time already and I'm the first one to report this behaviour, I assume it actually works like you suggested and there's just something wrong with my setup. Unfortunately, I don't have time to investigate it closer, so I'm closing this issue.

**Comment by afragen** [comment]
It's already set for a 5 day dismissal period. 

Can you look in your console To see if there's any errors when you dismiss the notice?

**Comment by chesio** [comment]
There are no errors, but I found out that the problem occurs only on websites with [Autoptimize](https://github.com/futtta/autoptimize) plugin active.

From what I have found, it seems Autoptimize is listening to the same AJAX action (`dismiss_admin_notice`) that is used in Git Updater: 

https://github.com/futtta/autoptimize/blob/ec755aad32b9b8fa70c48754d3f9bbca6688489f/classes/external/php/persist-admin-notices-dismissal/persist-admin-notices-dismissal.php#L47

I guess that Autoptimize's hook is executed instead of Git Updater's hook.

**Comment by chesio** [comment]
As far as I can understand the code, both plugins use the same framework for notices: https://github.com/w3guy/persist-admin-notices-dismissal I guess the issue is that the framework is not expected to be used by multiple plugins at the same time :-)

**Comment by afragen** [comment]
Thanks for the debugging. I'll have to see about what to do for that.

**Comment by afragen** [comment]
Hmm, makes sense as my library is an updated version.
