### ISSUE TITLE
GitHub personal access token gets deleted randomly / periodically from Git Updater settings

### ISSUE THREAD

**Issue by BjoernKW** [afragen/git-updater#1023]
My GitHub personal access token for my WordPress instance gets deleted randomly / periodically from the Git Updater settings under "GitHub Personal Access Token", which results in this error message:

> Git Updater Error Code: 403
> GitHub API’s rate limit will reset in 50 minutes.
> It looks like you are running into GitHub API rate limits. Be sure and configure a [Personal Access Token]
> (https://help.github.com/articles/creating-an-access-token-for-command-line-use/) to avoid this issue.

Setting the token again fixes the error, only for it to reappear after some time.

**Comment by afragen** [comment]
https://git-updater.com

Without a license there are no authenticated API requests.
