### ISSUE TITLE
Support the `Update URI` field in headers too

### ISSUE THREAD

**Issue by jeliebig** [afragen/git-updater#1025]
After reading this WP [blog post](https://make.wordpress.org/core/2021/06/29/introducing-update-uri-plugin-header-in-wordpress-5-8/) I was looking for a plugin to add GitHub update URI support to WP and stumbled over this plugin!

From the README I understand the `Update URI` header is currently not used to check for updates.
Without reading through the code I'm guessing it probably also doesn't use the `update_plugins_{$hostname}` filter which was described in the blog post as well.

Would it be possible to add support for this header field as well?

In order to keep compatibility with the `Github Update URI` header, I don't want to suggest replacing it.

**Comment by afragen** [comment]
I've utilized the header system I have for a long time before the `Update URI` header has been in core. Both headers may coexist and if you wish to integrate with Git Updater I believe a more intentional integration is better.
