### ISSUE TITLE
Continuous 403 rate limit error

### ISSUE THREAD

**Issue by MSEGitHub** [afragen/git-updater#1026]
I am at a loss. For the past couple of months, every day (starting around 2:00pm EST) I am receiving rate limit errors and do not know why. I do have a personal token set. I also reached out to GitHub and this is what they said:

Over the course of one week there were 491105 API calls with 87% going to <code>/repositories/:repository_id/tags</code> endpoint. Second place was only 7%.

The actual offending URL is : <code>https://api.github.com/repos/mystudioengine/woocommerce-bookings/tags</code> which accounts for 82% of the calls with nothing else breaking 0.3%. They said there were one hour periods where this URL only broke over 6000 API calls.

I tried deleting the repository and recreating but it didn't change anything. I'm not sure why this URL is the only one with an issue or how to fix it. Any help would be greatly appreciated.

**Comment by afragen** [comment]
What version of Git Updater are you using and do you have a license?

**Comment by MSEGitHub** [comment]
I had one last straggler site running 10.x but I just upgraded him. Everything else is running either 12.0.0 or 12.0.2.
And yes, we do have a license.

**Comment by afragen** [comment]
Have you entered a personal access token in the GitHub tab? If so these errors are usually cached for an hour to avoid pounding GitHub. Select Refresh Cache after the access token has been saved. 

https://git-updater.com/knowledge-base/troubleshooting/

**Comment by MSEGitHub** [comment]
Yes, we've been using a personal access token since almost the beginning. It is currently configured using the <code>gu_set_options</code> hook.

**Comment by afragen** [comment]
Can you log in as the organization an create an access token?

**Comment by afragen** [comment]
https://github.com/afragen/git-updater/issues/979 might help too.

**Comment by MSERobert** [comment]
If I had a bad token, wouldn't it always be bad? Meaning, when I'm not under "rate limit" I can refresh the cache and update all plugins with no problems. I've also replaced the token with a newer formatted one some time ago.

I bypassed WP-Cron and with query monitor running, while under "rate limit" there were no 404 errors in the console.

**Comment by afragen** [comment]
You aren't using v12.0.3.1 are you? That's the `develop` branch. I just fixed an issues I caused.

**Comment by afragen** [comment]
> If I had a bad token, wouldn't it always be bad? Meaning, when I'm not under "rate limit" I can refresh the cache and update all plugins with no problems. I've also replaced the token with a newer formatted one some time ago.

You are correct.
 
> I bypassed WP-Cron and with query monitor running, while under "rate limit" there were no 404 errors in the console.

Was the initial problem with 403s using Git Updater v12+?

**Comment by afragen** [comment]
I ask as I've started caching those types of errors for an hour so I don't pound the GitHub API.

**Comment by MSERobert** [comment]
No, 12.0.2 is the latest version I'm running. Actually this issue started before v12, (I just kept hoping it would go away.)

It's funny, I do know when the problem is occurring because I have this error in the console (always the same URL):
![image](https://user-images.githubusercontent.com/63687283/213803602-23052a95-88a3-48e6-9fe4-e6201fd83936.png)

**Comment by afragen** [comment]
Can you give me some sort of `read` permissions for that  repo so I can test?

**Comment by MSERobert** [comment]
Absolutely, you should be set.

**Comment by afragen** [comment]
<img width="1188" alt="screenshot_271" src="https://user-images.githubusercontent.com/1296790/213831033-454eeb83-fed2-4a56-93b0-12ec0a4b553a.png">

**Comment by MSERobert** [comment]
How about now? I'm currently being blocked for the next 50 minutes.

**Comment by MSERobert** [comment]
I'm getting it now:
![image](https://user-images.githubusercontent.com/63687283/213833095-0b918748-e18c-408a-8d30-178be7fef9bd.png)

**Comment by afragen** [comment]
Do you have a license? If yes, you shouldn't have rate limiting.

**Comment by afragen** [comment]
Having a GitHub.com Access Token set should keep you from rate limits and allow access to the private repo.

Do you have this set?

**Comment by MSERobert** [comment]
Yes to both. We have a license from you and I do have a token set. But that's the problem, the token gets you 5000 hits an hour, correct? According to GitHub that one URL I mentioned above sometimes accounts for more than 6000 hits in one hour.

If you want to catch it when it's failing, the bottom of the hour is the best time.

**Comment by afragen** [comment]
Any response code other than 200 should be cached for a hour. https://github.com/afragen/git-updater/blob/90308b65e1d336144b4ca828c4e580622ec5d677/src/Git_Updater/API/API.php#L191

**Comment by afragen** [comment]
I'm seeing a strange issue where some data is not being saved to the cache. Investigating.

**Comment by afragen** [comment]
I found the issue. Parsing and then serializing your readme.txt can yield slightly different data at times that results in a variance that doesn't allow the cache to be saved. The reason for this is the extreme size of your readme.txt file. By limiting the changelog in the readme to the current year only, the cache gets correctly saved and these extra API calls will stop.

**Comment by MSERobert** [comment]
Holy crap, I'm so glad you found something. Thank you so much for your help. And it's only the readme.txt file?

**Comment by afragen** [comment]
As far as I can tell. Even dot org recommends readme file be under 10k. My recommendation is to keep the changelog separate as you do and remove the changelog from the readme.txt file. If you name your changelog file as follows, Git Updater should parse it correctly, though I'm not certain given the size of your changelog. I'd give it a shot.

https://github.com/afragen/git-updater/blob/90308b65e1d336144b4ca828c4e580622ec5d677/src/Git_Updater/Base.php#L407
