### ISSUE TITLE
Personal Access Tokens Seem to Randomly Get Deleted

### ISSUE THREAD

**Issue by scottfennell-toptal** [afragen/git-updater#1029]
Hello,

Today is the fourth time in the past month or so when I've loaded the GHU screen and seen this:

<img width="2048" alt="Screenshot 2023-01-25 at 5 48 01 PM" src="https://user-images.githubusercontent.com/34286895/214709759-d119a415-38d0-48e6-80cd-1fc62eebda66.png">

Empty values for my personal access token, in all the form field inputs.  I'm not sure why this is happening.  It's annoying to have to keep generating a new token.

Maybe I'm doing something wrong but I can't make out what it might be.

**Comment by afragen** [comment]
Hey @scottfennell-toptal,

Git Updater v12+ has incorporated Git Updater PRO and Git Updater Additions. There is now an associated license. All details at https://git-updater.com

Free version doesn't do authenticated API requests. There is a month trial period to see the benefit of authenticated API requests. That trial period must have elapsed.

**Comment by BWBama85** [comment]
We don't need a month trial to see the benefit since it was a feature you now have removed to make a quick buck from people.

**Comment by afragen** [comment]
https://github.com/afragen/git-updater/issues/1030#issuecomment-1459060642
