### ISSUE TITLE
When plugin update is available it resets to an old version

### ISSUE THREAD

**Issue by woutr-nl** [afragen/git-updater#1031]
The plugin-version was 1.0.3-beta and 1.0.4-beta is available.
After updating it's back to 1.0.1-beta somehow..

![image](https://user-images.githubusercontent.com/16634704/214878236-7192cb63-cc4f-4045-bf2a-68271a27acad.png)

**Comment by afragen** [comment]
Are you tagging releases? If yes and the release isn't the same version as your default branch this can happen. 

https://git-updater.com/knowledge-base/settings/
