### ISSUE TITLE
Deprecation warning triggered in WP 6.2 due to Request Library update

### ISSUE THREAD

**Issue by montagmorgens** [afragen/git-updater#1036]
After updating to WordPress 6.2, Git Updater triggers the warning

```The` PSR-0 `Requests_...` class names in the Request library are deprecated. Switch to the PSR-4 `WpOrg\Requests\...` class names at your earliest convenience.```.

This seems to be related to an [update in the WP Request Library](https://make.wordpress.org/core/2023/03/08/requests-library-upgraded-to-2-0-5-in-wordpress-6-2/), also see https://core.trac.wordpress.org/ticket/57350.

**Comment by afragen** [comment]
I have also seen this intermittently. I only use the `wp_remote_*` calls and never directly call `Requests` so I'm not sure what triggers this.

I'll comment on the Trac ticket.

**Comment by chesio** [comment]
It seems to be the `WP_Dismiss_Notice` class - see the stack trace below. As far as I can tell, it seems to save response from `wp_remote_head` call in a transient, so when this pre-WordPress-6.2 transient is fetched from database, it is unserialized in an array with instances of old `Requests_*` classes.

```
#0 [...]/wordpress/wp-includes/Requests/src/Autoload.php(161): bc_backtrace()
#1 [internal function]: WpOrg\Requests\Autoload::load('Requests_Respon...')
#2 [internal function]: spl_autoload_call('Requests_Respon...')
#3 [...]/wordpress/wp-includes/functions.php(649): unserialize('a:6:{s:7:"heade...')
#4 [...]/wordpress/wp-includes/option.php(253): maybe_unserialize('a:6:{s:7:"heade...')
#5 [...]/wordpress/wp-includes/option.php(911): get_option('_transient_wp-d...')
#6 [...]/wordpress/wp-content/plugins/git-updater/vendor/afragen/wp-dismiss-notice/wp-dismiss-notice.php(42): get_transient('wp-dismiss-noti...')
#7 [...]/wordpress/wp-includes/class-wp-hook.php(308): WP_Dismiss_Notice::load_script('site-health.php')
#8 [...]/wordpress/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#9 [...]/wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#10 [...]/wordpress/wp-admin/admin-header.php(118): do_action('admin_enqueue_s...', 'site-health.php')
#11 [...]/wordpress/wp-admin/site-health.php(96): require_once('/var/www/birgit...')
#12 {main}
```

**Comment by montagmorgens** [comment]
I can confirm that. After deleting the transient, the warning goes away.

**Comment by afragen** [comment]
I think I have this fixed in the `develop` branch. Can you use branch switching to test it. You will also need to delete the `wp-dismiss-notice_jsurl` transient.

**Comment by afragen** [comment]
Fixed in https://github.com/afragen/git-updater/commit/269a6059366c092ea662ec76f2d5fc38b2a5d5c6

**Comment by hirasso** [comment]
Hi there! I also just observed this problem (plugin version: `12.2.1`, wp version: `6.2`). Dumping `$error_get_last` inside `admin-header.php` gives me the following info:

```php
array(4) {
  ["type"]=>
  int(16384)
  ["message"]=>
  string(158) "The PSR-0 `Requests_...` class names in the Request library are deprecated. Switch to the PSR-4 `WpOrg\Requests\...` class names at your earliest convenience."
  ["file"]=>
  string(81) "/Users/rah/Sites/pratergalerie/wwwroot/core/wp-includes/Requests/src/Autoload.php"
  ["line"]=>
  int(171)
}
```
When I deactivate GitHub updater, the error is not being thrown.

**Comment by afragen** [comment]
Hmm, I thought I fixed this. 

https://core.trac.wordpress.org/ticket/57350

I'll take a closer look.

**Comment by afragen** [comment]
Is there a full stack trace for this?

**Comment by hirasso** [comment]
I think I figured out what's going on. As you described in the ticket on wordpress.trac, the problem was the transient. It was still there after the plugin update. So running this fixed it for me:

```
wp transient delete --all
```
I guess the solution would be to add an update hook for the plugin that will delete the old transient?

**Comment by afragen** [comment]
Or I could take the lazy way and just wait for the transient to timeout. 😉
