### ISSUE TITLE
GitHub fine-grained access tokens strange behavior

### ISSUE THREAD

**Issue by iamcryptoki** [afragen/git-updater#1038]
Hi,

We are experiencing a strange behavior with your plugin when we use the new GitHub fine-grained access tokens. 

Git Updater works fine when we add the token for the first time on each site (more than 30 sites!), but the "GitHub.com Access Token" field becomes empty a few minutes later, and the synchronization no longer works with GitHub repositories.

We do not want to use the classic access tokens as they offer no control over tokens within the GitHub organization.

**Comment by afragen** [comment]
Can I ask if you have a current license to Git Updater?

**Comment by afragen** [comment]
Fine grained tokens are still in beta and I haven't yet tested to determine what settings are required. As they are more restrictive it's likely they may need to be entered on a per repository basis.

**Comment by iamcryptoki** [comment]
Yes, we do! Our license has been active for about 2 years.

**Comment by iamcryptoki** [comment]
We performed another test by entering a token for a specific repository, but the field for this token is empty again after 24 hours.

**Comment by afragen** [comment]
This license has only existed for less than 6 months.

**Comment by afragen** [comment]
I have tested GitHub's fine grained personal access tokens and they work with Git Updater.

https://git-updater.com/knowledge-base/settings/#articleTOC_4
