### ISSUE TITLE
Version 12.1.3 and WordPress 6.2 causes PHP error in backend (PHP8.0)

### ISSUE THREAD

**Issue by KodeksAS** [afragen/git-updater#1041]
In the WordPress backend we get this error after updating WordPress to the newest version (6.2). I have done troubleshooting and the error class disappears when disabling Git Updater plugin.

```
PHP Notice:  Function wp_cache_flush_runtime was called <strong>incorrectly</strong>. Your object cache implementation does not support flushing the in-memory runtime cache. Please see <a href="https://wordpress.org/documentation/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 6.1.0.) in /[redacted]/wp-includes/functions.php on line 5865
```

Do you have any clue how it can be fixed? Before updating WordPress we had no issues :)

**Comment by afragen** [comment]
This function is not called anywhere in the Git Updater code.
