### ISSUE TITLE
'We made a few tweaks to the plugin, Opt in to make "Git Updater" better'! link broken

### ISSUE THREAD

**Issue by 24Degrees** [afragen/git-updater#1042]
In the dashboard, after install, you get the notification:

We made a few tweaks to the plugin, [Opt in to make "Git Updater" better!]

The link this is refering to: 

https://deidealeschool.be/wp-admin/settings.php?page=git-updater 

is not working.

**Comment by afragen** [comment]
Are you one a multisite?

**Comment by afragen** [comment]
So in taking a look at this. Git Updater must be Network Activated in multisite.

**Comment by afragen** [comment]
https://git-updater.com/knowledge-base/multisite-activation/

**Comment by 24Degrees** [comment]
Ok thank you very much, plugin works smooth now, keep up the good work!
