### ISSUE TITLE
Problem of CSS layout in changelog tab

### ISSUE THREAD

**Issue by herrvigg** [afragen/git-updater#1043]
I'm not 100% sure this comes from git-updater, but the layout is wrong with a huge empty space in the changelog tab (when a new version is available).
Sorry for big screenshot but that's the only way to show how it looks.

### Screenshot

![github-updater-changelog](https://user-images.githubusercontent.com/19155375/235372727-9639ae9f-c97a-4c37-81fa-cf3e1ebe05d6.JPG)

**Comment by herrvigg** [comment]
I looked at the CSS and some values look quite bad with these huge numbers (99999px).

![github-updater-changelog-css](https://user-images.githubusercontent.com/19155375/235372935-7d0b829b-cf50-4c87-ad55-f8130565505e.JPG)

By setting `0px` to the third value in the `padding` of `#section-holder` it solved the problem. This should be better adjusted but it's just to say it can be fixed.

**Comment by afragen** [comment]
Git Updater does not provide any CSS or styling for that. It's all the core modal.

**Comment by afragen** [comment]
I find using `####` for the changelog entries work well.

**Comment by herrvigg** [comment]
Hard to test without doing a new release, do you know if it works with `###` (3) ?

> Git Updater does not provide any CSS or styling for that. It's all the core modal.

That's what I suspected. I see a reference to `section-holder` here:
https://github.com/afragen/git-updater/blob/39b9ce6cdab6bfcab7696d5caf40c857159aaf74/vendor/freemius/wordpress-sdk/includes/fs-plugin-info-dialog.php#L1503

Not sure it's the same but it's an external package in wordpress-sdk so I close this. I'll try to report it there because this is CSS design done wrong 😕

**Comment by herrvigg** [comment]
But first I need to understand where it comes from. At first sight I thought this was an official WordPress SDK plugin https://github.com/Freemius/wordpress-sdk. But it looks rather like a third-party plugin?
