### ISSUE TITLE
Version number issue: Version: 0.2.41 does not update to Version: 0.2.5

### ISSUE THREAD

**Issue by 24Degrees** [afragen/git-updater#1044]
A good evening everyone,

Not a big issue and a workaround available but still reporting: 

I just found out that if you use version number 0.2.41 for your theme and later update to Version: 0.2.5, Github updater will not detect a newer version.

Fix: use 0.2.50 so make sure to always have the same number of digits.

**Comment by afragen** [comment]
Semantic versioning is used and version_compare() is used to determine updates. 

0.4.4 < 0.4.4.1
0.4.4.1 < 0.4.5
0.4.5 < 0.4.10
etc
