### ISSUE TITLE
404 Error can't get updates

### ISSUE THREAD

**Issue by adamjbragg** [afragen/git-updater#1046]
I can't get the plugin to work with the paid upgrade, a GitHub Token and my primary branch set to main. 

my theme headers are style.css

```
Theme URI: https://github.com/adamjbragg/wp-liquid-instruments
Primary Branch: main
```

these are my token settings

```
repo
repo:status
repo_deployment
public_repo
repo:invite
security_events
write:packages
read:packages
```

dev console outputs this 404

```
settings.php:2746     GET https://dev.liquidinstruments.com/wp-content/themes/wp-liquid-instruments/vendor/afragen/wp-dismiss-notice/js/dismiss-notice.js?ver=6.2.2 net::ERR_ABORTED 404
```

Any ideas?

Thanks.

**Comment by afragen** [comment]
A 404 error is an authentication error. Please try a copy/paste reset of your token or perhaps create a new token.

**Comment by adamjbragg** [comment]
Thank for the response. I really should have check the headers more closely. I've updated the updated the header and can now see my theme, and pushed changes seem to come through. 

Now I get an error saying:

`Update failed: Download failed. Destination directory for file streaming does not exist or is not writable.` 

I'm working with a clients setup and server, not my own setup.

**Comment by adamjbragg** [comment]
Fixed on my end. Thanks for your help.
