### ISSUE TITLE
An error occurred while updating WebHeroe: Update package not available.

### ISSUE THREAD

**Issue by AlvaroAcha** [afragen/git-updater#1047]
Hello,

I did create a theme to be updated through git updater.

I did update the style.css and upgrade version. The update appears in WordPress admin panel, but when I try to update it I get the following error:

An error occurred while updating WebHeroe: Update package not available.

Thank you

**Comment by afragen** [comment]
I believe you opened this issue in Slack. Let's continue there as it will be faster.

**Comment by AlvaroAcha** [comment]
Hello @afragen, thank you for your answer.

I will check it and reply on Slack

:)

**Comment by afragen** [comment]
Remove the `Release Asset` header from your repo. You don't have a build process and it causes issues. 

https://git-updater.com/knowledge-base/required-headers/#articleTOC_1
