### ISSUE TITLE
Persistent license reminder on network admin screens on multisite installs

### ISSUE THREAD

**Issue by herrschuessler** [afragen/git-updater#1050]
I have installed and licensed the plugin on a multisite install (entering the license key in each of the multisite sites), but the licensing reminder (_Please consider purchasing a Git Updater license ..._) is still showing on the network admin screens.

**Comment by afragen** [comment]
The dependency installer framework was never meant to work with multisite. 

My recommendation is to get a copy from https://git-updater.com and install/activate as network admin. You may need to temporarily deactivate the plugin/theme that is requiring and loading it via the installer.
