### ISSUE TITLE
Cron refresh never finishes

### ISSUE THREAD

**Issue by MSERobert** [afragen/git-updater#1051]
I have a multisite where refreshing the cache never finishes. This message is displayed on the page:
![image](https://github.com/afragen/git-updater/assets/63687283/08b5446e-8ecf-4af0-b95b-162a1042406d)

If I look at the wp-cron list I can see the plugin and theme jobs at the top of the list. If I refresh the page they never leave but the run time changes.
![image](https://github.com/afragen/git-updater/assets/63687283/b22c8f3e-7464-4611-922d-e2f7976187df)
![image](https://github.com/afragen/git-updater/assets/63687283/83198aa2-2401-4e9c-8aed-a37b84c032f9)

If I manually try to to run the cron, I get the following message:
![image](https://github.com/afragen/git-updater/assets/63687283/22e9e2c6-42a5-4d0d-b008-4113c97289ba)

I also uninstalled the plugin to see if there were any stuck jobs but the crons were removed when the plugin was uninstalled.
Is there anything else I can check or do to kickstart this?

Thank you,
Robert

**Comment by afragen** [comment]
You can check the he setting to bypass background processing. 

https://git-updater.com/knowledge-base/troubleshooting/
