### ISSUE TITLE
Possible to include branch name in assets?

### ISSUE THREAD

**Issue by crftwrk** [afragen/git-updater#1054]
Hi,

our plugins using `-main` branch in release assets zip file, for example `plugin-name-main.zip`.

If we use Git Updater, plugin `-main` folder is removed and plugin is installed twice which leads into a fatal error.

Is it possible to include the `-main` in Git Updater? Found something for `$tags` in the knowledge base, but this is not what we are searching for.

Thanks in advance

**Comment by afragen** [comment]
Plugin zip files have a containing folder that is equivalent to the plugin slug and is installed in `wp-content/plugins`. The name of the zip file doesn't matter. 

Git Updater intentionally ensures that the download package is correctly renamed to abide by WordPress standards. 

Downloads from GitHub will incorrectly install the plugin with the branch name in the slug. Git Updater fixes this. It would seem that you may have installed the plugin at least once from a direct download. 

If you ever need to install a plugin or theme from GitHub you should use the Install Plugin tab in Git Updater and it will correctly manage the proper folder naming.

**Comment by crftwrk** [comment]
Got it, thank you 🙏
