### ISSUE TITLE
GitHub Access Token disappears 

### ISSUE THREAD

**Issue by Hube2** [afragen/git-updater#1056]
The GitHub Access Token (for private repos) value on every site I use this on never sticks. I must constantly re-enter the value.

The missing Token value causes continuous errors in the server error log

[10-Nov-2023 07:45:03 UTC] Git Updater Error: {PLUGIN NAME} ({PLUGIN SLUG}) - Not Found

**Comment by afragen** [comment]
Do you have a license?

**Comment by aaronsummers** [comment]
I'm also experiencing the same issue with my licence activated.

**Comment by Hube2** [comment]
I have to buy a license to make the access key stop disappearing?
And stop this plugin from filling up my error logs with Not Found errors?

**Comment by afragen** [comment]
@Hube2 the plugin gives you 4 weeks to trial. After the trial you will no longer be able to use an access token. Purchasing a license provides that functionality. Please refer to https://git-updater.com
