### ISSUE TITLE
discouraged Improvements

### ISSUE THREAD

**Issue by ipajen** [afragen/git-updater#1058]
### Environment
- WordPress: 6.4.2
- PHP: 8.2.11
- Server: LiteSpeed
- Database: mysqli (Server: 10.6.15-MariaDB / Client: mysqlnd 8.2.11)
- Browser: Safari 17.1.2 (Mobile)
- OS: iPhone
- Theme: Twenty Twenty-Three 1.3
- MU Plugins:
  * ai1wm-max-select-records.php
  * block-automation-by-installatron.php
  * Health Check Troubleshooting Mode 1.9.1
- Plugins:
  * All-in-One WP Migration 7.79
  * Git Updater 12.3.0
  * Plugin Check (PCP) 0.2.2
  * Query Monitor 3.15.0
  * Test Reports 1.0.0
  * WordPress Beta Tester 3.5.5
  * WPVulnerability 3.0.0

When checking with  https://wordpress.org/plugins/plugin-check/ there is some improvements to be made. ( if not false positive)

file_get_contents() is discouraged. Use wp_remote_get() for remote URLs instead.

json_encode() is discouraged. Use wp_json_encode() instead.

parse_url() is discouraged because of inconsistency in the output across PHP versions; use wp_parse_url() instead.

The use of function base64_decode() is forbidden.

**Comment by afragen** [comment]
Discouraged is not an error.

I prefer and use the PHP native functions when they are available. They are all used correctly.

`json_encode()` and `parse_url()`, and `base64_decode()` are used correctly and I do plenty of error checking.
`file_get_contents()` is only used for local files.

I must decode base64 as GitHub sends some API responses encoded in base64.

Plugin Check is not perfect and doesn't take code in context.
