### ISSUE TITLE
Please be patient while WP-Cron finishes making API calls.

### ISSUE THREAD

**Issue by MSERobert** [afragen/git-updater#1060]
I am having a problem with one multisite setup (all other sites work fine). I have some settings saved in a plugin file. It knows about the "overridden plugins" but it does not seem to read the GitHub Access Token. If I manually enter and save the key, it works for a little while but the next day the key is empty again and the plugin is complaining.

I tried to uninstall and reinstall the plugin but the result was the same. We do have an active license. 
Any ideas what the problem could be?

**Comment by afragen** [comment]
Do you have a current license for Git Updater?

**Comment by MSERobert** [comment]
Yes we do.

**Comment by afragen** [comment]
What email was used to register the license?

**Comment by MSERobert** [comment]
It should be ***@***.***"

**Comment by afragen** [comment]
It might be better to proceed on the[Git Updater Slack](https://join.slack.com/t/git-updater/shared_invite/zt-1extq97hy-FjA1QAhjGNDzmFjjlRv3rg)  in DM.
