### ISSUE TITLE
Header information

### ISSUE THREAD

**Issue by herrfischerhamburg** [afragen/git-updater#1061]
In the wiki you say the theme needs a URI information in the header like "GitHub Theme URI: https://github.com/afragen/test-child"
Q: Do i need to use "Bitbucket Theme URI: https://github.com/afragen/test-child" when using Bitbucket?

I am asking because I don't get any updates on my theme.

**Comment by afragen** [comment]
Take a look at https://git-updater.com/knowledge-base/usage/

You need to adjust the header based upon the git host.
