### ISSUE TITLE
Dockerized Project - style.css not in the root of the repo

### ISSUE THREAD

**Issue by phil-sola** [afragen/git-updater#1063]
Hi,

I am using Docker for all WordPress projects and map the theme folder which is in the root of my repo to the themes directory inside the container. 

This means the theme's style.css is not in the root of the repo but inside the theme directory (1 level in).

/
theme
      - style.css
docker-compose.yml
etc.
etc.

This means that I keep getting an error "The package could not be installed. The theme is missing the style.css stylesheet."

I saw on another issue with the same issue you say you look for style.css in the root like WordPress but this doesn't take into account other setups where the style.css is perfectly within the right place for the theme, but the repo itself is structured differently for very valid reasons.

I would love to see you support theme locations within the repo URI to enable these edge cases to work.

**Comment by afragen** [comment]
So your theme is inside the Docker container?

**Comment by phil-sola** [comment]
My theme is within a docker container on the server yes. Inside wp-content/themes/my-theme

In my Bitbucket private repo my theme folder, is at the root of the repo, meaning the style.css file is within that theme folder (not in the root of the repo)

**Comment by afragen** [comment]
Git Updater is designed for plugins/themes that follow a standard where the plugin/theme is in a repository of its own. That doesn't mean you can't use it in a Dockerized container but it shouldn't primarily exist in the Dockerized container. 

https://git-updater.com/knowledge-base/usage/

**Comment by phil-sola** [comment]
Thanks Andy, appreciate that's how it works currently which is a shame but would there be any room for specifying a directory within the repo? 

Seems like an extra field could help a lot of people with different setups that aren't "wrong", just different to this standard.

**Comment by afragen** [comment]
Git Updater is designed to work the same way Core does and that's with a plugin or theme in their own folder inside the `wp-content/plugins` or `wp-content/themes` folder. 

If that structure is replicated on GitHub, Bitbucket, etc then the ability of Git Updater to read the API data of those plugins or themes becomes much simpler.

What is the direct URL to your theme's `style.css` on Bitbucket? If using that URL in the `Bitbucket Theme URI` doesn't work I'm not certain Git Updater will work for your setup.

**Comment by afragen** [comment]
> In my Bitbucket private repo my theme folder, is at the root of the repo, meaning the style.css file is within that theme folder (not in the root of the repo)

This should work. What is the problem? Can you give my user `afragen` access to the private repo to test?

**Comment by phil-sola** [comment]
Hey Andy, I don't think I'll be allowed as this is for the agency I work for so not code I own and not my bitbucket. 

If it should work, despite the style.css file not being in the root of the repo it's most likely something to do with how I've set it up.

I added a css header to my style.css file: Bitbucket Theme URI: https://bitbucket.org/<workspace>/<repo_name>

I pushed this to my staging branch for testing.

Within the plugin I tried to do 'Install Theme' on the Install theme tab, with the Bitbucket add-on installed.

Theme URI I entered the same: https://bitbucket.org/<workspace>/<repo_name>

For branch I entered staging

I entered my username and application pw.

When it runs, I get an error saying "The package could not be installed. The theme is missing the style.css stylesheet"

Perhaps I've done something wrong in the plugin or my style.css header?

**Comment by afragen** [comment]
Can you share the specific file structure of the repository?

**Comment by afragen** [comment]
Also, what is the file structure of the download?

**Comment by afragen** [comment]
Can you make a placeholder `style.css` file in the root that just has the same headers? By updating it he version number there as well updates would be seen.

**Comment by afragen** [comment]
Also, can you create a release asset that is just the theme folder and its contents?

Would then need to add the `Release Asset: true` header.

**Comment by phil-sola** [comment]
> Can you make a placeholder `style.css` file in the root that just has the same headers? By updating it he version number there as well updates would be seen.

How would this work with updating the theme from the theme directory in the repo? Would it not just look for the theme files in the root of the repo and fail again?

**Comment by afragen** [comment]
If there's private info you don't want to share in public please join the Slack and DM me. Link in the readme.

**Comment by afragen** [comment]
> How would this work with updating the theme from the theme directory in the repo? Would it not just look for the theme files in the root of the repo and fail again?

It would enable the API calls to read header data.

**Comment by phil-sola** [comment]
Thank you and sorry for the curveball! I'm extremely mindful of your time here. Appreciate the help so far

**Comment by afragen** [comment]
I happen to have some free time. Take advantage of it 😉

**Comment by phil-sola** [comment]
Thank you! I have created a private repo with the very bare structure on my personal bitbucket account here:

https://bitbucket.org/philsola/test-repo/

![image](https://github.com/afragen/git-updater/assets/40669220/392461d9-c67b-44bb-bb37-a9f34c3f970c)

![image](https://github.com/afragen/git-updater/assets/40669220/d86957db-84ea-46ed-8039-5376c11c41b9)

Only one branch - master

Do you need anything else?

**Comment by afragen** [comment]
Access to it would be great.

**Comment by phil-sola** [comment]
I tried adding you to the repo in Bitbucket but it couldn’t find afragen. Is there an email I should search by instead?

**Comment by afragen** [comment]
andy@thefragens.com

**Comment by phil-sola** [comment]
Done! Thanks

**Comment by afragen** [comment]
OK, I've got it working. The test-repo is updated with the examples. There were a number of changes.

1. The local repo name **must** be identical to the repository repo name. `test-theme !== test-repo`
2. Add a placeholder style.css at the root level of the repository. Headers should be same as `test-repo/style.css`.
3. Tag releases and ensure that a new release asset is uploaded to the Bitbucket repository. If you can create a CI Job to create this release asset we can use that but it will require another header.

Testing. 

1. [Download the release asset](https://bitbucket.org/philsola/test-repo/downloads/test-repo-1.0.1.zip)
2. Install as a theme by uploading to test site.
3. On test site, decrease the version number of the `style.css` to `1.0`
4. Refresh Cache in Git Updater
5. You should see an update available.
6. Go to update-core.php page and update the theme
7. Check that theme has updated version number and that no further updates display.

Every update will need to be tagged and a corresponding release asset only of the theme's containing folder must be  uploaded as a release asset.

**Comment by afragen** [comment]
BTW, if you use a default branch other than `master` it must be designated in a `Primary Branch` header.

**Comment by phil-sola** [comment]
Amazing, thanks so much for spending time on this Andy! really do appreciate it and it's interesting to see how you've got that working. 

Today has been flat out for me at work, but hoping to circle back round to this and get this now working! Thanks so much.

**Comment by afragen** [comment]
LMK if you have issues implementing this for your theme. It's a bit more work but should continue to work. Issues will be remembering to tag releases and create release assets for each tag. 

FWIW I think the API grabs the most recent release asset so the name might not be that important, just the recency.
