### ISSUE TITLE
Git-Updater website login

### ISSUE THREAD

**Issue by mmecaroni** [afragen/git-updater#1066]
Hi there.. need some help.. I bought your plugin months ago as I really need it to help me keep a single source codebase for my wordpress plugin and theme in a private github repo. When I first purchased it I configured it and got it working properly but it no longer works. I can not get private repos linked and some public.. I have a developer friend helping me and he got same issues, and mentioned it may be some kind of caching issue.. 

Is there anyway you could make a quick video tutorial on how to proper install this? I dont know if it is something we are doing wrong on our setup. If you would like, I would gladly get on a Zoom call with you and I will collaborate with you on making a tutorial video or something to help others in case they are having the same issue.

Also..I have tried to login to you website admin area to contact you and now i get the meesage that my user/email is "Error: There is no account with that username or email address." when I try to reset my password and get it.

**Comment by afragen** [comment]
https://git-updater.com is a reference/sales website. It is not meant to log into. The [Knowledge Base](https://git-updater.com/knowledge-base/) is quite extensive.

I'm happy to help with any issue you might have getting things working. Let's start with one of the public repositories. Can you share the URL and let me know precisely what the issue is?

**Comment by liquiddev03** [comment]
Hello **Afragen**, 

=>I am developer of Wordpress and working with Mr. Mecaroni, I used your pro plugins for github repo to Wordpress installation of plugins and themes. but its not working properly.
 => Sometime it will showing installed plugins and theme while installation success but sometime its showing red alert.
 => I followed complete tutorial that you provided on Knowledgebase page but its seems not working and I generate token with fully permission.
 => Here I am attaching some screenshots that I made today for issue represent.

**![Step-1]**(https://github.com/afragen/git-updater/assets/48906904/5261c759-4c26-4b29-a226-573e76e2e3a6)
**![Step-2]**(https://github.com/afragen/git-updater/assets/48906904/cd21ecd2-b753-4473-8e1c-ddd3ced34d8a)
**![Step-3]**(https://github.com/afragen/git-updater/assets/48906904/6b9d5751-cda5-40f6-9dd1-d247fe4b66d7)
**![Git-updater-issue]**(https://github.com/afragen/git-updater/assets/48906904/02107fe0-4ead-4c65-a9b0-630ab9f3cedd)
 You can just review and let me know what I am doing wrong to configuration 
 Thank you.

**Comment by afragen** [comment]
Have you placed all the correct headers in both the plugin and the theme? 

https://git-updater.com/knowledge-base/required-headers/

Can you give my user temporary access to the repositories so I can better help? If not can you provide a temporary access token for me to use?

**Comment by liquiddev03** [comment]
Yes my Github temporary user access is 
  User : hitesh@liquidsg.com
  Pass : Lwsdev@24#ketan
  I set all header but you can check if get better idea

**Comment by afragen** [comment]
It is possible to use the Install Plugin and Install Theme tabs with repositories that aren't setup to use Git Updater.

**Comment by liquiddev03** [comment]
Means I used Install plugin using token and its successfully installed from the Private Repo

**Comment by liquiddev03** [comment]
Did you see anything that need to correct on Git or setting in plugin?

**Comment by afragen** [comment]
I'm going to delete those messages with password access. Please email me or join the Git Updater Slack and DM.

**Comment by afragen** [comment]
It's better to keep this conversation going on Slack as the privacy is better.

**Comment by afragen** [comment]
Some of the resolved issues are the following:

- Repository must be lowercase as this is used for slug. Per plugin guidelines the slugs are all lowercase.
- Headers for Git Updater must be in main plugin file.
- Must use `Primary Branch` header if primary branch is not `master`
