### ISSUE TITLE
Download and install Git Updater in your WP theme or plugin

### ISSUE THREAD

**Issue by jessuppi** [afragen/git-updater#1068]
Thanks again for your amazing work @afragen 

I hope it's okay to mention this here because I don't see any other public examples. But if anyone needs a way to require Git Updater in your WordPress theme or plugin, and automatically download and install it from GitHub:

https://github.com/littlebizzy/hovercraft/blob/master/inc/git-updater.php

We are using this snippet in our free HoverCraft theme that is part of SlickStack and it is working very well...

Of course, feedback and criticism is welcome anytime. Thanks!

Ref: https://slickstack.io/forum/topic/automatically-install-and-activate-the-git-updater-plugin

**Comment by afragen** [comment]
I've actually created a library that is capable of automatically installing and activating a plugin. Take a look at https://github.com/afragen/wp-dependency-installer

**Comment by jessuppi** [comment]
That's awesome! I had come across that a while back, and apparently forgot about it. Thanks again!
