### ISSUE TITLE
Asking for FTP Credentials

### ISSUE THREAD

**Issue by mobiusint** [afragen/git-updater#1069]
Thanks for your awesome plugin. I ran into this issue all of a sudden and wondering if I have to adjust something in the settings. It's asking me for ftp credentials when trying to download the branch from bitbucket.

Screenshot.
https://capture.dropbox.com/tLlBtaGTVLoJ0e2P

Thank you in advance,

**Comment by afragen** [comment]
Answered in Slack. 

Short version, add the following to `wp-config.php`

```
define( 'FS_METHOD', 'direct' );
```
