### ISSUE TITLE
Create hook to point to 'api.wordpress.org` clone.

### ISSUE THREAD

**Issue by afragen** [afragen/git-updater#1071]
@JeffMatson has created/is in process of creating a clone of sorts for the plugin/theme/update repositories and an API to access them.

Git Updater, by design, checks to see if a plugin/theme is hosted on the official repository and if the Git Updater sees the plugin/theme is on the default branch it will preferentially update from the official repository. There is a hook to override this behavior. https://git-updater.com/knowledge-base/wordpress-org-directory/

It seems that if hosts will be providing their own clones of .org then Git Updater should be able to check and see if the plugin/theme exists there.

**Comment by afragen** [comment]
Working on this in branch [api-domain-hook](https://github.com/afragen/git-updater/tree/api-domain-hook).

**Comment by afragen** [comment]
Now in `develop`

**Comment by JeffMatson** [comment]
@afragen Ooooh man I love this!

Let's chat more too - I think we have some overlapping goals that could work really well together.

**Comment by afragen** [comment]
Absolutely!

**Comment by afragen** [comment]
Added in https://github.com/afragen/git-updater/commit/58c6a8e76e12e169cf748fb68289ef2e7435beea
