### ISSUE TITLE
Automated install script

### ISSUE THREAD

**Issue by hirasso** [afragen/git-updater#1072]
Hi there! Just thought to leave this here for future reference:

https://gist.github.com/hirasso/910ff58a1eccce7b64a385ddc1809c67

It's a script that allows to install a WordPress plugin from the latest GitHub release (as opposed to the latest commit on master/main). I'm using it mainly to automatically install `afragen/git-updater` on my websites, so that it can take over afterwards.

Anyways, thanks @afragen for your great work!

**Comment by afragen** [comment]
You can also. use WP-CLI to install directly from GitHub. All you need is the URI.

```php
wp plugin install https://github.com/afragen/git-updater/releases/download/12.6.0/git-updater-12.6.0.zip --activate
```

**Comment by hirasso** [comment]
Sure. But then I have to look up the latest release zip. No time for that...wait!! I can run `wp plugin update --all` immediately after! That actually sounds much much simpler 😄

**Comment by afragen** [comment]
In that case just use the zip for `master`.

**Comment by hirasso** [comment]
Does the master branch always match the code in the latest release?

**Comment by afragen** [comment]
For git-updater the master branch is the release branch.
