### ISSUE TITLE
Function _load_textdomain_just_in_time was called incorrectly

### ISSUE THREAD

**Issue by ipajen** [afragen/git-updater#1074]
Tested both master and dev version of the git-updater. Getting below doing it wrong warning with QM.

Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the git-updater domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the init action or later. (This message was added in version 6.7.0.)

`_load_textdomain_just_in_time()
wp-includes/l10n.php:1347
get_translations_for_domain()
wp-includes/l10n.php:1385
translate()
wp-includes/l10n.php:194
esc_html__()
wp-includes/l10n.php:339
Fragen\G\A\Settings->add_settings_tabs()
wp-content/plugins/git-updater/src/Git_Updater/Additions/Settings.php:124
Fragen\G\A\Settings->load_hooks()
wp-content/plugins/git-updater/src/Git_Updater/Additions/Settings.php:58
Fragen\G\A\Bootstrap->run()
wp-content/plugins/git-updater/src/Git_Updater/Additions/Bootstrap.php:55
Fragen\Git_Updater\Bootstrap->run()
wp-content/plugins/git-updater/src/Git_Updater/Bootstrap.php:99
Fragen\Git_Updater\{closure}()
wp-content/plugins/git-updater/git-updater.php:60
do_action('plugins_loaded')
wp-includes/plugin.php:517`

**Comment by afragen** [comment]
This is fixed in `develop`. It's removed as Git Updater doesn't bundle translations but loads them into `wp-content/languages/plugins` so the JIT loading works.

**Comment by afragen** [comment]
This seems to be anywhere a translation function like `esc_html__` is loaded before `init`.

**Comment by afragen** [comment]
I think https://github.com/afragen/git-updater/commit/07f317e61c074f92c738c756d0794384e9aee2aa should fix the issue.

**Comment by ipajen** [comment]
Yes the fix seems to fix the issue. Thanks!

**Comment by afragen** [comment]
That change in WP6.7 has bitten many people.
