### ISSUE TITLE
WPEngine hosted websites don't show or update themes using GitUpdater any more.

### ISSUE THREAD

**Issue by aaronsummers** [afragen/git-updater#1075]
Hi Andy,

On WPEngine, my theme shows a "hosted on WordPress" badge and no longer shows when the theme has a new CSS version as an update in the site's backend.

My theme is hosted on Bitbucket in a private repository and was until recently updating without a problem.

**Comment by aaronsummers** [comment]
No HTTP errors. 
I control the versions using the CSS version in styles.css. 
I haven't used tags to push updates.

**Comment by afragen** [comment]
I’ve now had several users have issues with theme updates on WPE. Working on it.

**Comment by hybridwebdev** [comment]
> I’ve now had several users have issues with theme updates on WPE. Working on it.

Might this be an issue related to the drama between Mullenweg and WPE? Perhaps they're blocking the self-updating hook when on WPE?

**Comment by afragen** [comment]
It very well might be related, especially as this issue didn't previously exist.

**Comment by afragen** [comment]
I think I have a solution. It seems the WPE API is incorrectly returning an HTTP 200 code when checking to see if a theme exists on dot org.

I have made a plugin to override this behavior. Please install the Gist API plugin from the API Plugins tab and then Install/activate the following plugin.

https://gist.github.com/afragen/a007e35ff54e33ae92a2397f089ae8a3

**Comment by afragen** [comment]
This should be fixed in v12.7.0

**Comment by aaronsummers** [comment]
Thanks, Andy. I believed this was a WPEngine issue related to their dispute with Automatic. I wondered if WPEngine did this to bypass WordPress, blocking them from allowing plugin and theme updates from the WPEngine servers.

**Comment by afragen** [comment]
What I found was that WP API returns a 404 if the plugin or theme isn't in the repo if checked. WPE's solution returns a 200 whether or not the plugin/theme exists. 

I was checking for this. I had to change what I was looking for. Slightly more time expensive but not much else to do.
