### ISSUE TITLE
Branch switching not working for GitLab repositories

### ISSUE THREAD

**Issue by grahamrb-ed** [afragen/git-updater#1076]
Hi, just purchased Git Updater. We've enabled the branch switching feature and are using **GitLab**.

The plugin is able to pull through the list of branches however when selecting a branch to switch to the result is a 404 error. Looking at the URL that it is fetching it is using `?SHA=branchname` but should instead use `?BRANCH=branchname` for GitLab.

**Comment by grahamrb-ed** [comment]
Apologies, I've just found the separate repo for the GitLab plugin. I think it's a one-line change here: https://github.com/afragen/git-updater-gitlab/blob/3bbf185ec25fe4981ed5498de42238bdfe1858a4/src/GitLab/GitLab_API.php#L210

**Comment by afragen** [comment]
Can you reference in the GitLab API where this changed?

I'll test also.

**Comment by grahamrb-ed** [comment]
Thanks. We've done some more testing and it looks like something intermittent on the GitLab end. Sometimes we get a 404 back from GitLab and sometimes it worked. I think it just happened that it gave a 404 with sha and so we tried branch= and it worked.

**Comment by afragen** [comment]
404 is usually an authentication issue, but if it's intermittent it could be on GitLab's end.
