### ISSUE TITLE
Why isn't this allowed in the wp.org plugin repo?

### ISSUE THREAD

**Issue by notslang** [afragen/git-updater#34]
Sorry if this has been asked before, but I couldn't find an answer in the other issues and the line in the repo is really vague:

> This plugin is not allowed in the wp.org repo. :frowning:

**Comment by limikael** [comment]
Quoting @slang800 

> peer review isn't how you gain safety - it's by sand-boxing plugins and giving them a responsible API -like chrome does with the permissions API. Of course, this isn't really possible with PHP, but that's how you'd actually solve this problem.

Out of interest I googled a bit and found this:

http://php.net/manual/en/runkit.sandbox.php

Using that, would it in theory be possible to create a sandboxed environment for wordpress plugins? One where the only way for the plugins to communicate with the rest of the system would be through a well defined api. And then the plugins would have to request permissions, like an iPhone or Android app, such as "this plugin wants to read user data", "this plugin wants to access database table such and such", "this plugin wants to create its own database tables", "this plugin wants to read and write files in directory such and such", etc... This would obviously be a HUGE thing, but has someone else thought along those lines?

**Comment by GaryJones** [comment]
Since it's not bundled with PHP by default, not everyone will have it.

**Comment by limikael** [comment]
But that wouldn't stop us from imagining it and thinking about it, right? It would be possible to imagine a solution where plugins are sandboxed if this PHP extension is installed, and otherwise the plugins are not sandboxed and the user would be warned about this. Sorry btw if this was out of context, I was just curious about if someone knew something about this and if there was maybe a discussion about this in some other place...

**Comment by GaryJones** [comment]
If you want to create a local or production environment for your own sites that run plugins ins sandboxes, go for it. It's nothing something that would be part of WP Core, nor GitHub Updater, so this isn't the place to discuss it in-depth.
