### ISSUE TITLE
Update 8.0.0 removed github-updater

### ISSUE THREAD

**Issue by AlphaDE** [afragen/git-updater#696]
After upgrading to 8.0.0 via WP Plugin manager as suggested, I got 

The plugin github-updater-develop/github-updater.php was deactivated due to an error: the plugin file does not exist.

Seems the updater broke itself while updating.

The plugin removed obviously itself during the update process and failed to install itself again.

After manually copying to update into the respective directory, there are now two entries of the updater in the WP plugin list.

**Comment by afragen** [comment]
The solution is to fix the directory name from `wp-content/plugins/github-updater-develop` to `wp-content/plugins/github-updater`. 


That being said I’ll have to check as previously it was handling the renaming and reactivation correctly. 

Is this the first time you’ve updated GitHub Updater?

**Comment by afragen** [comment]
An you provide a link to WP plugin manager?  I’m not familiar with it.

**Comment by AlphaDE** [comment]
Yes, that was the first time, the updater updated itself. 

The directory was properly renamed to github-updater... but Wordpress remembers the path and if the path is changed, the plugin gets deactivated by Wordpress (as the plugin file is not longer available under its original path). 

When using the release .zip to install via Wordpress plugin manager (download the zip, select manual install, select the zip and install), it does not use "github-updater", but it installs to "github-updater-8.0.0". The path in the release zip should use the same directory structure as the plugin itself

**Comment by afragen** [comment]
If you use the branch switcher and switch to the branch you want, it will reinstall that branch and it should correctly rename and reactivate the plugin. 

It’s possible that the first update does as you experienced and results in a plugin deactivation but it should then be renamed correctly and all subsequent updates should just work.

**Comment by afragen** [comment]
Once GitHub Updater is installed you should never need to re-install from a zip file. Just reinstall using the branch switching.

**Comment by AlphaDE** [comment]
I later saw that the error was caused by a directory name change... I assumed the plugin was deleted and reinstalled it...

**Comment by afragen** [comment]
It can be confusing. I guess by now I’ve seen similar messages so often it simply doesn’t phase me. As long as I can explain why it happened I’m good. 

Everything now working as expected?
