### ISSUE TITLE
Consultation on Remote Management

### ISSUE THREAD

**Issue by franzarmas** [afragen/git-updater#707]
Hello, according to the github-updater Wiki for Remote Management there is an overload for users with role 'administrator', but my question is .. what capacity (for example it can be: 'update_core') is checked to validate that overload?

I commented, I have created a new role called 'owner' with certain capabilities very similar to the role 'administrator' .. but I want this new role, is not affected to the possible overload that affects the administrators, so so .. what is the capacity that must NOT have the role 'owner' so that there is no possible overload?

Please, I could clarify more details on this topic.
I would appreciate it very much.
Thank you!

**Comment by afragen** [comment]
GitHub Updater only runs under the following user privileges.

https://github.com/afragen/github-updater/blob/e6d5d18e6f56ed69b5ee7a3ca5c19c49ff36d897/src/GitHub_Updater/Init.php#L118

This being said. When WP-Cron is being used, which has been the default for several major releases, even with an administrator there shouldn’t be a significant slowdown.

**Comment by afragen** [comment]
There is no filter for this. Only the users who can `manage_networks` or `manage_options` can run GitHub Updater. Those are capabilities that only network administrators for multisite or administrators on a single site install have.

**Comment by franzarmas** [comment]
I understand, could you create a filter to modify the capabilities in a next version of github-updater ?? ..
I would greatly appreciate it.

**Comment by afragen** [comment]
Actually in looking at how you’re using the filter it looks like it could work. But this might open it up for individual administrators on a multisite. I haven’t checked.

**Comment by afragen** [comment]
The user would still need the above privileges in addition to any other restrictions you’ve just placed.

**Comment by afragen** [comment]
Adding a filter like that would be a big security risk. Any random plugin could then allow for any user to be able to utilized GitHub Updater.

**Comment by franzarmas** [comment]
I understand, what happens is that my role 'owner' has that capacity (manage_options) added .. and I do not want github-updater not to load for users with role 'owner' ..

I consider using the 'update_core' capability instead of 'manage_options' .. I think a user with the 'update_core' capability looks more like a global administrator.

What do you suggest doing to prevent github-updater from loading for users with the 'owner' role?

**Comment by afragen** [comment]
Out of curiosity what capabilities does `owner` have that `administrator` doesn’t. The reverse as well.

**Comment by franzarmas** [comment]
These are the capabilities of the role `owner`.

```php
$capabilities_owner = [

	// Administrator
	'delete_users'       => true,
	'edit_users'         => true,
	'edit_theme_options' => true,
	'list_users'         => true,
	'manage_options'     => true,
	'promote_users'      => true,
	'remove_users'       => true,
	'customize'          => true,
	'create_users'       => true,

	// Editor
	'moderate_comments'      => true,
	'manage_categories'      => true,
	'manage_links'           => true,
	'edit_others_posts'      => true,
	'edit_pages'             => true,
	'edit_others_pages'      => true,
	'edit_published_pages'   => true,
	'publish_pages'          => true,
	'delete_pages'           => true,
	'delete_others_pages'    => true,
	'delete_published_pages' => true,
	'delete_others_posts'    => true,
	'delete_private_posts'   => true,
	'edit_private_posts'     => true,
	'read_private_posts'     => true,
	'delete_private_pages'   => true,
	'edit_private_pages'     => true,
	'read_private_pages'     => true,
	'unfiltered_html'        => true,

	// Author
	'edit_published_posts'   => true,
	'upload_files'           => true,
	'publish_posts'          => true,
	'delete_published_posts' => true,

	// Contributor
	'edit_posts'   => true,
	'delete_posts' => true,

	// Subscriber
	'read' => true,
];
```

**Comment by afragen** [comment]
From what you said above it seems like you want GHU to load for `owner` and it will.

**Comment by afragen** [comment]
Are those only for a single site install?

**Comment by franzarmas** [comment]
What I want is the opposite ... that GHU does not charge for `owner`.. only `administrator`

Yes, it is a single installation.

**Comment by afragen** [comment]
If you set `manage_options => false` for owner then it won’t run. Otherwise your `owner` has the same privileges as `administrator`

**Comment by afragen** [comment]
If using the above filter the `owner` would likely see negligible impact though it might appear that GHU is loaded for them.

**Comment by franzarmas** [comment]
Ohh ... I understand.

As I said I think that validating `update_core`,` update_plugins`, or `update_themes` is more logical since the GHU is more about updates and / or installations ... I think 'manager_option' does not necessarily go aligned with the GHU objective.

I hope you can consider it for a future release ... I would appreciate it.

**Comment by franzarmas** [comment]
Thank you very much for this @afragen , GHU is great ...

I remain attentive to the next release, greetings!
