### ISSUE TITLE
Not found on private bitbucket

### ISSUE THREAD

**Issue by petertwise** [afragen/git-updater#757]
Hi - 

I'm having trouble updating from a private bitbucket account.

This looks like the same symptoms from https://github.com/afragen/github-updater/issues/739 but I'm using the latest version that includes that fix. (Version 8.6.1 with WP 5.0.3)

The short error message when updating from the themes page is:
`Update Failed: Download failed. Not Found`

The longer message when updating from the updates page is:
`Downloading update from https://bitbucket.org/squarecandy/[myreponame_redacted]/get/?pagelen=100&sort=-namemaster.zip…
An error occurred while updating Greenagers: Download failed. Not Found`

I rolled back and tested with 8.6.0 and everything worked as expected. Then I updated again to 8.6.1, manually changed the theme version back one on the server (for testing), and tried again and got the error again.

Any help much appreciated. Thanks for the great plugin.

**Comment by squarecandy** [comment]
Tested and works great - thanks!
