### ISSUE TITLE
Problems getting updates to show

### ISSUE THREAD

**Issue by milojennings** [afragen/git-updater#81]
I cannot for the life of me figure this out. I've tried bitbucket, and github repos. I've tried several different installations of WordPress. I've tried using tags, using different branches. For whatever reason it just doesn't notice any updates, no matter what I do.

Is there anything obviously wrong with this?
https://github.com/roadsidemultimedia/sms-headings/blob/master/sms-headings.php

**Comment by jeremytarpley** [comment]
So glad I found this thread, adding $args['timeout'] = 600; to class-github-updater.php fixed updating for me!  I was pulling my hair out trying to figure out why it wasn't updating!

**Comment by afragen** [comment]
Where did you add this? If I can get it to work consistently I'd appreciate a PR. :smile:

**Comment by milojennings** [comment]
**Update**

For me, I can now confirm that the Pagelines Updater plugin immediately causes a conflict as soon as I activate it and enter my developer license. 

Updates will be working fine with the Github Updater plugin, but as soon as I enter my license key into the Pagelines Updater, Github Updater ceases to function. I've posted a support request in there forum here: http://forum.pagelines.com/topic/38216-pagelines-updater-preventing-github-updater-from-working/

**Comment by afragen** [comment]
@milojennings can you email me a copy for the Pagelines Updater plugin? Does just the activation cause the issue?

**Comment by milojennings** [comment]
@afragen you should be able to download it here: http://www.pagelines.com/api/store/v3/pagelines-updater.zip
