### ISSUE TITLE
Conflict with Easy Updates Manager

### ISSUE THREAD

**Issue by nicomollet** [afragen/git-updater#910]
Hello,

I heavily use Github Updater for my WP Github repos.
It works great but I wanted to have other features from Easy Updates Manager (Premium version).
Free version is here https://fr.wordpress.org/plugins/stops-core-theme-and-plugin-updates/
Premium offers "updates schedule frequency" and "delay updates".

It allows me to set updates only on monday nights for example. And also delay 1 day the updates in case to avoid broken versions from some plugins. 

But these features don't work when Github Updater is enabled: frequency and delay don't respect my settings (it also updates on tuesday afternoons).
When  Github Updater is disabled, my frequency and delay settings are respected.

So there is a conflict between the two plugins.
Is it something impossible to fix? Two plugins managing updates simply can't live together, so I have to choose between the two?
I know Easy Updates Manager hooks inside `wp_update_plugins`.

I would like to have your opinion on that?
Thank you

**Comment by afragen** [comment]
GitHub Updater hooks into the `set_site_transient_update_plugins` hook to insert its data into the core update methods. There is no ability to set a delay though the API data from GitHub, etc is cached for 12 hours. 

It might make more sense to create an issue with EUM. I don't have/use EUM Premium. If there's something they discover please refer them back here.

**Comment by nicomollet** [comment]
@afragen I gave up using Easy Updates Manager since there are more options in the WP core since 5.5 I think.
Closing the ticket.
