### ISSUE TITLE
GitHub Actions

### ISSUE THREAD

**Issue by afragen** [afragen/git-updater#915]
It seems that Travis CI usefulness is nearing an end. I could use some help and a PR for switching over to using GitHub Actions. 

Any help is appreciated.

**Comment by shivammathur** [comment]
Hi, I saw your tweet and have created a PR #916. Hope it helps

**Comment by afragen** [comment]
It worked perfectly. Now I need to figure out how to create a release asset for a tagged release.

**Comment by afragen** [comment]
It must be possible to set the phpunit version to correspond to the php version.

**Comment by shivammathur** [comment]
See PR #917

**Comment by shivammathur** [comment]
Also created PR for attaching release asset #918

**Comment by afragen** [comment]
You are awesome! Thank you so much.

At some point I'll be asking about testing with PHP 8.0 also, I'll have to see if I can figure out how to add it.
