### ISSUE TITLE
Parsedown.php error

### ISSUE THREAD

**Issue by jbleys** [afragen/git-updater#938]
Hi,

First, thanks for this plugin. It's a most helpful tool to manage custom plugins and themes.

I ran into a strange issue between Github Updater and one custom plugin of my own. All the sites that I manage where both plugins are active broke down with the same error:

`Recoverable fatal error: Object of class stdClass could not be converted to string in /wordpress/wp-content/plugins/github-updater/vendor/erusev/parsedown/Parsedown.php on line 30`

This happened after a new update to my custom plugin was pushed to bitbucket, but _before_ it was updated to the various sites. The specific commit can be viewed here: 
https://bitbucket.org/uwdgh_elearn/uwdgh-admin-columns/commits/a4ec79127005ed9acbff00984be9cd0670701217

I'm unsure why this commit triggered the Error manifestation in Github Updater. Perhaps it's something obviously faulty in my plugin. I'm just not seeing it.

I managed to resolve the issue on each site by updating my plugin through WP-CLI.

Anyway, I thought it was strange enough to report. Let me know if you need/want more information.

Kind regards,
Jasper Bleijs
University of Washington

**Comment by afragen** [comment]
Strange as the plugin readme validator shows some errors but nothing that should cause a problem. This is a probably an issue with the readme format as this is what gets passed to Parsedown. FWIW I'm using the plugin readme parser.

Unless I can replicate this I'm not sure what to do.

**Comment by jbleys** [comment]
Thanks for taking a look. I'll review my readme and see what can be improved there. I'll let you know if I find any more details.
