### ISSUE TITLE
Branch main

### ISSUE THREAD

**Issue by hupe13** [afragen/git-updater#939]
Hi,
thank you for your plugin. The API don't work right in the admin inteface, the branch of my plugin on Github is "main", but Github updater asks for "master":  Output from Query Monitor:
GET | https://api.github.com/repos/myplugin/my-plugin.php?ref=master | 404 Not Found
(because it is "main")
<pre>   Fragen\G\API->api()
    wp-content/plugins/github-updater/src/GitHub_Updater/API.php:199
    Fragen\G\API->get_remote_api_info()
    wp-content/plugins/github-updater/src/GitHub_Updater/Traits/API_Common.php:128
    Fragen\G\A\GitHub_API->get_remote_info()
    wp-content/plugins/github-updater/src/GitHub_Updater/API/GitHub_API.php:60
    Fragen\G\Base->get_remote_repo_meta()
    wp-content/plugins/github-updater/src/GitHub_Updater/Base.php:298
    Fragen\G\Plugin->get_remote_plugin_meta()
    wp-content/plugins/github-updater/src/GitHub_Updater/Plugin.php:259
    Fragen\G\Base->get_meta_plugins()
    wp-content/plugins/github-updater/src/GitHub_Updater/Base.php:182
    Fragen\G\Base->load()
    wp-content/plugins/github-updater/src/GitHub_Updater/Base.php:172
    do_action('init')
    wp-includes/plugin.php:484
</pre>

**Comment by afragen** [comment]
https://github.com/afragen/git-updater/wiki/Settings#primary-branch

You need to set the header `Primary Branch: main`.

**Comment by hupe13** [comment]
Thank you very much, now it is ok. I set in the header "* GitHub Branch: main" until now and now I set "* Primary Branch: main" also.

**Comment by afragen** [comment]
There is no header `GitHub Branch`.
