### ISSUE TITLE
Update package not available error

### ISSUE THREAD

**Issue by digino** [afragen/git-updater#941]
I try to setup the plugin on my website for remote management and continuous integration of custom theme. I follow the wiki indications. The theme was in private repository but i make sure i setup a token. But after curl test i got this error :
{
    "success": false,
    "data": {
        "messages": ["Update package not available."],
        "webhook": {
            "key": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
            "theme": "gerbb",
            "webhook_source": "browser"
        },
        "elapsed_time": "350.44 ms",
        "deprecated": false
    }
}

In the settings of the plugin, i got the message : "This repository has not connected to the API or was unable to connect". But after few hours of search, i don't find what to do.
Help please.

**Comment by afragen** [comment]
Is the primary branch of the repo `main`?

if so you need to add the `Primary Branch: main` header to your main file.

**Comment by afragen** [comment]
Fundamentally the process must work in the dashboard for it to work with a Webhook.

**Comment by digino** [comment]
Excuse me for the late reply
**Is the primary branch of the repo main?**
Yes

**if so you need to add the Primary Branch: main header to your main file.**
How can I do it please?

**Fundamentally the process must work in the dashboard for it to work with a Webhook.**
I tried to uninstall and reinstall using Mr. Mikael Lindqvist's procedure. But I still have nothing.

**Comment by afragen** [comment]
https://github.com/afragen/git-updater/wiki/Settings#primary-branch

**Comment by afragen** [comment]
https://github.com/afragen/git-updater/wiki/Settings#primary-branch

**Comment by digino** [comment]
Problem solved. Thank you very much for your help and good luck to you.

**Comment by digino** [comment]
Hi M. Andy
I retry to setup the plugin for remote management. But from the webhook
page i got this error "Webhook tag and current branch are not matching.
Consider using `override` query arg.".
I don't understand it. Please help
Thank you

Le mar. 20 avr. 2021 à 14:01, Andy Fragen ***@***.***> a
écrit :

**Comment by afragen** [comment]
This means that the installed branch is different from the branch the webhook is trying to use so it errs, if you want to switch the branch in the webhook you need to add the `&override` to the webhook.

**Comment by afragen** [comment]
BTW, in the near future this will be a premium feature.

**Comment by digino** [comment]
I take advantage of it in advance so lol !
Awesome, thanks!
