### ISSUE TITLE
401 Unauthorized: Updater Translations

### ISSUE THREAD

**Issue by askinne2** [afragen/git-updater#943]
Hi,

This could perhaps be total user error, but I am receiving 401 Unauthorized for 
https://api.github.com/repos/afragen/github-updater-translations/contents/language-pack.json 

And as a result, the API for Git Updater is not finishing and seeing the updated version of my plugin in my personal repository.

Is this related to the rebrand?

**Comment by afragen** [comment]
When I click on that link in it correctly returns the result.

Do you have a GitHub personal access token set? Is it an _updated_ token, GitHub recently changed it's format for these and required a reissue of the token.

**Comment by askinne2** [comment]
Hi Andy,

Yes - I even refreshed the tokens listed below and am still receiving the error. Perhaps my privileges are incorrect? I forgot where I found those in the Wiki of how to set up the access levels...

Thanks for your help!

<img width="340" alt="Screen Shot 2021-04-21 at 10 26 08 AM" src="https://user-images.githubusercontent.com/23566039/115579657-fe90fa00-a28b-11eb-9f12-04afadafdbe0.png">

**Comment by askinne2** [comment]
My bad. I realize now that I needed a new Personal Access token for GitHub.com not my own repos or yours. Please mark as solved and my apologies for wasting your time. Love the plugin btw. Thanks!!
