### ISSUE TITLE
Update 2.1.8 available, and Git Update not updating?

### ISSUE THREAD

**Issue by askinne2** [afragen/git-updater#944]
Hey - Very sure this is user error, but I can't seem to pinpoint the problem. You wrote the plugin, so I'm assuming you can point in the right direction. It's like I'm stuck in an endless loooooop of not updating. Git-Updater says update available (v2.1.8). I click update in WP. It says update successful, and then my custom plugin stays at v.2.1.5)

See below for  screenshots

![Screen Shot 2021-05-01 at 9 17 15 PM](https://user-images.githubusercontent.com/23566039/116799975-9e3b5d00-aac2-11eb-9059-4d8b68af1ed8.png)
![Screen Shot 2021-05-01 at 9 17 59 PM](https://user-images.githubusercontent.com/23566039/116799995-b90dd180-aac2-11eb-8c4d-ddea4d0003a1.png)
![Screen Shot 2021-05-01 at 9 18 19 PM](https://user-images.githubusercontent.com/23566039/116800004-c3c86680-aac2-11eb-824f-6b9d148425e0.png)

So then, I tried releasing a higher version number (2.2.0) since I thought my understanding of PHP versioning might be off. Alas, now I've ruined everything. I am now receiving "Download Not Found"

![Screen Shot 2021-05-01 at 9 35 32 PM](https://user-images.githubusercontent.com/23566039/116800258-2d497480-aac5-11eb-8fe1-f9534b714e59.png)

Plugin URI: https://github.com/askinne2/GHHS-Animals
Latest Tag: https://github.com/askinne2/GHHS-Animals/releases/tag/v2.2.0

Any advice you can offer would be great! Thank you :) 

The header at the top of my plugin file:

```
<?php
/**
 * @link              https://github.com/askinne2/GHHS-Animals
 * @since             1.0.0
 * @package           [ghhs_animals]
 *
 * @wordpress-plugin
 * Plugin Name:       GHHS Animals
 * Plugin URI:        https://github.com/askinne2/GHHS-Animals
 *
 * Description:       Displays all animals that are currently listed in Greater Huntsville Humane Society's database in Shelterluv on website.
 *
 *
 * Version:           2.1.8
 * Author:            Andrew Skinner
 * Author URI:        https://www.21adsmedia.com
 * License:           GPL-2.0+
 * License URI:       http://www.gnu.org/licenses/gpl-2.0.txt
 * Text Domain:       ghhs_animals
 * Domain Path:       /languages
 * GitHub Plugin URI: https://github.com/askinne2/GHHS-Animals
 */
```

**Comment by afragen** [comment]
Here's the problem. You are tagging releases but you've recently changed the format of your tag. 

Previously you were tagging using semver, 2.1.3, 2.1.2, etc. You then changed to using v2.1.5, v2.1.8, etc. 

Tags are sorted high to low and that change by adding the `v` in front of your tag is now causing issues as the sort order has changed and now `2.1.3` is sorting the highest. The plugin returns the highest sorted tag. 

The solution is to delete and re-tag.

**Comment by askinne2** [comment]
Thank you good Sir. One thing that I did notice in attempting to troubleshoot this issue on my own:

If you manually delete a plugin via FTP that was installed via Git-Updater, a Cron job gets stuck in the queue that can never run again. It just lingers there until a manual remove of the Cron Job via WP Crontrol, etc. 

Is this something you're aware of ?

**Comment by afragen** [comment]
If you look inside the cron job there's no data. It's normal 😉
