### ISSUE TITLE
Why not using a private method to get Git URL?

### ISSUE THREAD

**Issue by waqasy** [afragen/git-updater#945]
In the documentation its mentioned that we need to put Git Repo URL in style.css. Which is very explicit. 

Can't there be an option to save the repo URL into WP options table?

**Comment by afragen** [comment]
Why clutter up the options table? Adding a single header line to the plugin or theme headers is pretty simple.

**Comment by afragen** [comment]
If you really don't want to add the header you can use the Git Updater Additions plugin to add the header. 

https://github.com/afragen/git-updater-additions

**Comment by waqasy** [comment]
> Why clutter up the options table? Adding a single header line to the plugin or theme headers is pretty simple.

Understood about that. I also love the simplicity.
