### ISSUE TITLE
Closed Issue Still a problem?

### ISSUE THREAD

**Issue by askinne2** [afragen/git-updater#946]
Hey man - I hate to be a bother, but this is an issue again, my tagging system looks fine? My latest release is 2.2.2 (no "v" in the tagging system, but I hit update inside the WP dashboard and the plugin reverts to an original version. Im stuck in an update loop again....

_Originally posted by @askinne2 in https://github.com/afragen/git-updater/issues/944#issuecomment-838787891_

**Comment by askinne2** [comment]
I am on version 2.2.0 right now. Trying to update to 2.2.2

Perhaps I have found the issue? For whatever reason, on the live site, I do not see a GitHub tab on the Git Updater Settings page. See screenshot below.

<img width="1128" alt="productionsite" src="https://user-images.githubusercontent.com/23566039/117893050-4e595480-b27f-11eb-9644-f199716681b0.png">

Now compare to the local installation of the exact same site using MAMP on my local machine where I do my development work. The Git Updater is installed there, and on the Settings page, I see a connection to GitHub with my custom plugin listed.

<img width="1154" alt="localhosting" src="https://user-images.githubusercontent.com/23566039/117893052-4ef1eb00-b27f-11eb-873f-89130b22b769.png">

Do you have a fix for this issue? My guess would be to delete plugin and reinstall using Git Updater?

**Comment by afragen** [comment]
Check the box to Bypass WP-Cron. You might have an issue getting WP-Cron to run.

**Comment by askinne2** [comment]
okay, that allowed the GitHub tab to show. Thanks, I can now update.

I realize this might be outside the scope of your plugin support directly, but do you have any advice on troubleshooting those issues with WP Cron.

**Comment by afragen** [comment]
I use the WP-Crontrol plugin.
