### ISSUE TITLE
How to add a plugin/theme with version 10

### ISSUE THREAD

**Issue by Eliophot** [afragen/git-updater#948]
Hello,

With the new version of your plugin (v10), I can't find the forms to add a theme or a plugin.
![image](https://user-images.githubusercontent.com/81296123/118633727-1055b680-b7d2-11eb-9ac8-ec7fb5884112.png)
How to do this?

Thanks

**Comment by afragen** [comment]
Installing plugins and themes is a now a **premium** feature. It is found in the Git Updater PRO plugin. 

You can get a free trial for the Git Updater PRO plugin from the **Add-Ons** tab.

**Comment by afragen** [comment]
I'm trying to explain more of this here, https://git-updater.com/knowledge-base/updating-from-github-updater-to-git-updater/

The site, https://git-updater.com , has lots of more info.

**Comment by Eliophot** [comment]
Seriously ? ok I fork it. Thanks...
