### ISSUE TITLE
Upgrade from 9.10 to 10.0.1 broke the plugin

### ISSUE THREAD

**Issue by bret-miller** [afragen/git-updater#950]
I upgraded from 9.10 to 10.0.1 using the WordPress dashboard. The result was the plugin was deactivated and when I tried to activate, it said, "Plugin deactivated, plugin file missing."

I was able to re-upload the zip and replace it to get it working but this might break everyone's installation...

**Comment by afragen** [comment]
Just re-activate the plugin. This message `"Plugin deactivated, plugin file missing."` will be present until the plugin finishes its renaming process. This is normal and will occur twice, I think.

**Comment by bret-miller** [comment]
So basically everything stops updating until everyone notices their plugin got deactivated and reactivates it multiple times until it's successful? I have about a dozen friend who use this that aren't savvy enough to do this without help. Oh well. I guess I know what to tell them at least.

**Comment by afragen** [comment]
There's no automated way to make this happen. With the rebranding I made a conscious decision to rename everything.

**Comment by afragen** [comment]
I'm trying to address these issue here, https://git-updater.com/knowledge-base/updating-from-github-updater-to-git-updater/

If I'm missing something or the instructions aren't clear, please let me know.
