### ISSUE TITLE
A bit confused about branch switching moving to PRO

### ISSUE THREAD

**Issue by therealgilles** [afragen/git-updater#951]
I know it's great to be paid for software you develop but it's a bit unusual for a free plugin to lose functionality it used to have and have it become premium. Still appreciate having the free functionality available :)

PS: I think the name change and related problems should be highlighted on the plugin github home page.

**Comment by afragen** [comment]
The Readme has a link to the Knowledge Base on the website, https://git-updater.com

The site is also referenced on the home page here. 

Was there something else you were looking for?

**Comment by therealgilles** [comment]
I think considering a lot of people may stumble onto the renaming issue with the message that plugin was disabled due to an incorrect header, it may be good to have a specific message about it.

**Comment by afragen** [comment]
I added a paragraph explanation of the deactivation/reactivation upgrade process at the top of the GitHub readme.

**Comment by therealgilles** [comment]
Very much appreciated :)
