### ISSUE TITLE
PHP error after disabling WP Cron

### ISSUE THREAD

**Issue by herrschuessler** [afragen/git-updater#952]
After upgrading to Git-Updater 10, I activated the plugin setting _Bypass WP-Cron Background Processing for Debugging_ .

Afterwards, any options on the settings page disappeard and the following PHP error was thrown.
```
Fatal error: Uncaught Error: abs(): Argument #1 ($num) must be of type int|float, string given
in /wp-content/plugins/git-updater/src/Git_Updater/Settings.php on line 637
```

Also, the submit button in the GitHub tab below the API token form disappeared after acitvating the WP-Cron bypass.

**Comment by afragen** [comment]
What version of PHP are you using?

**Comment by afragen** [comment]
I believe this is a change from PHP8 where `abs()` previous accepted a `mixed` value and now only accepts `int|float`.

v10.0.2 should fix this for you. Please let me know.
