### ISSUE TITLE
Can I have multiple plugins in one repo?

### ISSUE THREAD

**Issue by JBCSU** [afragen/git-updater#954]
I have a repo with multiple plugins. The root of repo is `wp-content/plugins`, and there are several plugins under the root. I'd like to use git-updater to keep them up to date. But the fact that the *GitHub Plugin URI* refers to a repo vs. a directory within a repo makes me think each of my plugins has to live in its own separate repo. Is that true? Is there any way to keep multiple plugins in a single repo and still have git-updater keep them up to date?

**Comment by afragen** [comment]
GitLab has something called projects.  Essentially it's a group of repositories.

I have tried it before. It might work if you structure it properly. Something like a repository of repositories. Each individual project would need to be in its own containing directory.

I'll have to test this out and see how it works. I can certainly see a use case. Especially as I just created 6 repositories for language packs.

**Comment by JBCSU** [comment]
Thanks @afragen . Glad you can see a use case. I look forward to learning how you experiments go.

**Comment by afragen** [comment]
I've tried many ways on GitHub for this but it doesn't work.

It does work on GitLab and if you require this type of feature I would recommend moving those repositories over there. In GitLab they are called Groups and you can _group_ multiple projects/repositories in a group. 

The schema would be `GitLab Plugin URI: <owner>/<group>/<repo>`. I know this works as I've been using it to test with for years. 😉
