### ISSUE TITLE
API Token not recognized for 2nd theme

### ISSUE THREAD

**Issue by stkjj** [afragen/git-updater#955]
generated an API token for a customer website. Used the token as general github.com Access-Token as well as for the private repo that hosts the theme.

Interestingly enough: both themes are private. One does not explicitly asked for a token, the other one refuses to connect.

![Screenshot 2021-05-25 um 15 52 58](https://user-images.githubusercontent.com/832642/119501706-c93b6880-bd71-11eb-9a02-38dc2a5d93e2.jpg)

Were's my error?

**Comment by afragen** [comment]
In the Settings, check the bypass of WP-Cron. It will allow some of the error notices to display. 

You might also install Query Monitor and see what the HTTP error is. 

Post those results here.

**Comment by afragen** [comment]
It's likely the token you have for the second theme is invalid.

**Comment by stkjj** [comment]
Hi, thanks for guiding me to Query Monitor which helped a lot! It was because of the branch named "main" whereas Git-Updater now seems to only support "master". As much as I understand this limitation of switching branches only for the paid Pro version I would love to see that the default "main" could also be supported. Remember the not so long ago discussion about master/slave perception with that naming? Maybe be not sticking to a certain name, but whatever the default branch is?!

**Comment by afragen** [comment]
Git Updater supports whichever branch name you chose as the primary branch. It does require, for any branch not `master`, to add an extra header to the main plugin or theme file. 

`Primary Branch: main`

**Comment by afragen** [comment]
https://git-updater.com/knowledge-base/versions-branches/
