### ISSUE TITLE
Can't see tabs on WPEngine hosted site after upgrade

### ISSUE THREAD

**Issue by shoreline-chrism** [afragen/git-updater#956]
Just updated to v10.x. I upgraded the site on a yet-to-be-live production environment on WPEngine and the tabs aren't showing up.  I installed wp-crontrol and triggered the associated hooks wp_update_themes() and wp_update_plugins() and i could see the functions hooked up, but it does nothing.  I also bypassed wp-cron for debugging through the option and saved changes, refreshed caches, ran those same hooks and the tabs to install plugins or themes aren't showing up.  Everything else seems to be there.  

There is no obvious error in the logs.  I even uninstalled the plugin completely, re-installed the new version fresh with the same results.  

The only thing I can think of is I see in the "Scripts" pane in query monitor, that a dependency, 'heartbeat' is missing.  This was happening with the new version, too, but I think it's related to WPEngine's stack which might disable heartbeat on it's own for some other solution so the sites aren't hammered on their servers.

<img src="https://i.imgur.com/Ogd7Hu8.jpg"/>

The image below is on the v9.10.0 plugin, but the same error was there on new plugin.  Any thoughts anyone? I wish I had more info to give you but I'm not seeing anything in the logs.  Here's some environment info:

*WordPress*
Version	5.7.1
Environment Type (Help)	production
WP_DEBUG	false
WP_DEBUG_DISPLAY	true
WP_DEBUG_LOG	false
SCRIPT_DEBUG	false
WP_CACHE	true
CONCATENATE_SCRIPTS	undefined
COMPRESS_SCRIPTS	undefined
COMPRESS_CSS	undefined
WP_ENVIRONMENT_TYPE	undefined

*Server*
Software	Apache
Version	Unknown
Address	127.0.0.1
Host	pod-140095:apache2_74:201
OS	Linux 5.4.0-1043-gcp

**Comment by afragen** [comment]
Can you screenshot the Settings page?

**Comment by shoreline-chrism** [comment]
I checked the bypass wp-cron and clicked save, refresh caches, ran the events again associated with this plugin and nothing still.

<img src="https://i.imgur.com/bUrxScR.jpg"/>

<img src="https://i.imgur.com/exiunfl.jpg"/>

<img src="https://i.imgur.com/teyYuCN.png"/>

**Comment by afragen** [comment]
The update from GitHub Updater 9.x to Git Updater 10.x renames the plugin files. Consequently the plugin automatically deactivates and will need to be reactivated, probably twice, to complete the renaming.

https://git-updater.com/knowledge-base/updating-from-github-updater-to-git-updater/

The fact that I still see the `wp-content/plugins/github-updater/...` in the error means that the plugin hasn't completed it's renaming.

Reverting  back and forth between these versions is likely to be an issue.

Is there an issue with the Git Updater 10.x installed and active? It should be `wp-content/plugins/git-updater/git-updater.php`

**Comment by afragen** [comment]
BTW, what missing tabs are you referring to?

https://git-updater.com

**Comment by shoreline-chrism** [comment]
The "Theme" and "Plugin" tabs where I used to install my plugins from
GitHub.com

**Comment by afragen** [comment]
The update and rebrand split the plugin into core and premium features. 

Plugin and theme installation is now in the premium feature set. Please take a look at https://git-updater.com for loads more information.

**Comment by shoreline-chrism** [comment]
That's unfortunate. I work for a small business and your tool has been
great, but I guess I'll just stick to WP-CLI for now. Thanks for your
previous work on the plugin before the split.

Since I'm one of the only developers who could touch the repos of our
plugins it was nice to be able to delegate some installation and upgrade
tasks to some content and SEO team members.

**Comment by shoreline-chrism** [comment]
I struggle to get buy-in from some team members for git at all and this was
a nice real-world tie-in. Really bummed. I'll try to see if my boss wants
to spend $300/ month

**Comment by afragen** [comment]
Unlimited license is $300/year not month. 😉

**Comment by shoreline-chrism** [comment]
I feel like installing and updating plugins is CORE functionality.  I can no longer install plugins from a github.com repo.  It feels like you've completely ripped any usefulness from this plugin.  And made worse, I now have dozens of inactive updated versions of this plugin on websites that I need to remove and I have to spend days now to rework my entire regimen. I have to bring a site local, git checkout my plugins and rsync them up.

Really, truly, disheartening.

**Comment by shoreline-chrism** [comment]
I understand your position and agree that you should have made a pro
version of the plugin.  My only argument is that installing and updating
the plugin through the wordpress admin area is the core feature of this
product.  As a small development team (3 developers, 3-4 content/seo
persons) that works on primarily local small business websites, I'm not
sure if my boss will justify the cost.  I think the price is fine for a
larger team, it just won't work for ours.

I'm sorry for giving you grief, but there's been a lot of talk lately about
these plugins just up-and-changing and leaving developers in the lurch
(like WP User Avatar) and I've been a little sensitive to the matter.

I'll just upload plugins via a ZIP file from github and use the plugin to
update them for now.  I wish you luck-- it is clearly an essential tool if
I'm crying about it so much.



Chris Matthias
Lead Developer at Shoreline Media Marketing
A  607 Lake Ave., Asbury Park, NJ 07712
P  (888) 591-8205 Ext. 106 <(888)+591-8205>
E  ***@***.***
W  https://www.ShorelineMediaMarketing.com
<https://www.ShorelineMediaMarketing.com?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>

Awarded Best Web/SEO Agency 2017, 2018, 2019
<https://www.facebook.com/shorelinemedia?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<https://www.linkedin.com/company/shoreline-media-marketing/about?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<https://twitter.com/shorelinemedia?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<https://www.instagram.com/shorelinemedia/?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<https://youtu.be/p1bvu0hEWfQ?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>

**Comment by afragen** [comment]
Chris, I hope your boss understands the value Git Updater PRO brings to you and your team. $300 for an unlimited yearly license doesn't seem like a lot, especially given the time it will save you.

You are saving what sounds like several hours of work and allowing some of that work to be done by others. I don't license it this way, but that's less than $1.00/day.

**Comment by afragen** [comment]
@pattyok The free plugin allows dashboard updates for any plugin or theme that contains the appropriate header and resides in GitHub, Bitbucket, GitLab, Gitea, or any of their self hosted versions. I hardly think this is worthless. 

Which documentation are you referring to? There's a whole website with information. https://git-updater.com

I'm curious why you think the core plugin is not useful?

**Comment by pattyok** [comment]
It seems to have stopped working in my case. It recognizes that there is an update but it wont actually make the update... without the tabs that were there previously its hard to troubleshoot. I do not use a master branch, so I don't know if that is my issue or not...?

**Comment by afragen** [comment]
Can you screenshot some of those things?

Are there any error notices?

**Comment by shoreline-chrism** [comment]
I agree that my initial reaction was based on the fact that I didn't understand the functionality changes.  And, while I don't agree with them, I do think the documentation needs to be clearer-- it wasn't clear to me that the major part of the plugin that I used it for was disappearing and that

**Comment by shoreline-chrism** [comment]
Didn't mean to close issue-- meant to say that I agree with the commenter. My immediate reaction was confusion because I didn't understand core functionality would be lost when i looked at the docs.  It could be a little clearer.

**Comment by afragen** [comment]
The core functionality is just that, core, it doesn't require the PRO plugin. 

If you're having issues with an update, please join the Slack and ping me.

**Comment by pattyok** [comment]
It recognizes there is an update:
![image](https://user-images.githubusercontent.com/2417080/120507173-6bafa900-c37b-11eb-928c-887348a39c8b.png)

It goes through making the update:
![image](https://user-images.githubusercontent.com/2417080/120507309-8b46d180-c37b-11eb-834e-915e6356a1d5.png)

Then on refresh it still indicates it needs an update:
![image](https://user-images.githubusercontent.com/2417080/120507433-a9accd00-c37b-11eb-81c4-0dd626e1a3e2.png)

No errors are indicated within the admin interface or the logs.

This is my header:
![image](https://user-images.githubusercontent.com/2417080/120507519-baf5d980-c37b-11eb-88b3-842ec51c977a.png)

**Comment by afragen** [comment]
@pattyok are you tagging your releases? If yes, are you tagging for each version?

**Comment by pattyok** [comment]
Yes, tagging releases, they match the version number. 
Also note that after the attempted update it reverts back to the last version that was updated prior to the update of the plugin (the last time that it worked). Which made me think that it would only work with the pro version. 

Not sure what you mean by the core update page and viewing the download url.

**Comment by afragen** [comment]
<img width="786" alt="screenshot_62" src="https://user-images.githubusercontent.com/1296790/120515078-cf89a000-c382-11eb-9535-d37406252503.png">

**Comment by afragen** [comment]
@pattyok the situation you're describing can easily happen if you forget to tag a release. When tags are present they are polled from the API and sorted using array_sort. The highest value (tag) is returned. If you've changed your style of tagging, ie, `v1.2.9` from `1.2.8` they will not sort how you think.

**Comment by afragen** [comment]
If you want to give me temporary access to your repo I might be able to figure it out quicker.

**Comment by afragen** [comment]
I'm closing this issue. If there are any other concerns please create a new issue.

**Comment by afragen** [comment]
FYI, I’m in the process of releasing a new model. Everything is back in the core plugin and there is no more need for the PRO plugin. I am monetizing the ability to use authenticated API requests. It’s only $20/yr unlimited number of sites. 

You can find a current pre-release at https://git-updater.com
