### ISSUE TITLE
Internal gitlab server over http: "no valid url provided"

### ISSUE THREAD

**Issue by ITaluone** [afragen/git-updater#957]
If I want to use our internal gitlab server (repos reachable over http://gitlab/user/repo) in every case the error "No valid URL provided" occurs.

I have tried also to use http://gitlab.domain.local/user/repo (FQDN) but also in this case the error from above.

Is this because the git* server have to be reachable over https?

Are there any debug logs which I can post here to provide further information?

Thank you

**Comment by afragen** [comment]
You don't need an FQDN, but you do need a valid, reachable URI from the computer you're testing on. 

You can have an internal IP of the local GitLab server if it's not set up with a host file alias.

**Comment by ITaluone** [comment]
Ok, the funny thing here: if I run "wget [generated URI]" on the same machine on cli it works. Meaning after that command I have an archive which is valid.

If I use the IP it does not work either.

**Comment by afragen** [comment]
What URI are you using? Does it bring up the repo in your browser?

When you say doesn't work, what precisely do you mean?

**Comment by ITaluone** [comment]
> What URI are you using?
The "main" URI of the repo. 

> Does it bring up the repo in your browser?
Yes

> When you say doesn't work, what precisely do you mean?
The error message in the title...
But if it helps: the error (in german)
![image](https://user-images.githubusercontent.com/44049228/120435046-8aaf3a80-c37d-11eb-8c6b-e7f53412ff2f.png)

**Comment by afragen** [comment]
So your local GitLab instance is reachable at http://gitlab ?

**Comment by afragen** [comment]
Can you try using the local IP address instead of the alias in the header?

**Comment by afragen** [comment]
> If so.. is there anything that I can do to debug this?

Other than stepping through the process in xdebug or something, I'm not sure. 

I use this with a local installation of Gitea and on a private instance of GitLab. 

Is the GitLab instance running on port 80?

**Comment by ITaluone** [comment]
> Is the GitLab instance running on port 80?

Yes

**Comment by afragen** [comment]
Unfortunately without being able to access the git host I have no real ability to troubleshoot this.

**Comment by afragen** [comment]
I may have come across a similar issue when testing something else. Take a look at this simple plugin and modify it for your site URL.

https://gist.github.com/afragen/ed00f34f8e03aeedb96bdbf6f3e50495

**Comment by ITaluone** [comment]
Thank you very much for that snippet! 

This solved my problem here.
