### ISSUE TITLE
What happened to install plugins from github?

### ISSUE THREAD

**Issue by Hube2** [afragen/git-updater#958]
Hopefully this is not something someone else already asked, but I can't find how to install a plugin from github any more. Where did it go?

**Comment by afragen** [comment]
With the rebranding to Git Updater I've split out premium features from the core plugin. The core plugin allows for dashboard updates of public or private repos. Everything else is a premium feature. 

Lots more info at https://git-updater.com

**Comment by Hube2** [comment]
That is disappointing. The only thing I use that would be considered premium (now I guess) is the ability to install from github without the dl and ul of .zip files. With the # of clients I have that means I'd need to spend $300 a year which would save me maybe an hour a year, if that. 

I'm not against people making a living and I hope you do well, but for me cost/benefit is too far out of balance.

**Comment by afragen** [comment]
I'm sorry. You can actually use WP-CLI directly to install a repository from GitHub. I'm just making many of these additional features much easier to accomplish.

**Comment by Hube2** [comment]
wp-cli not always possible and would save very little time or even take longer installing a single plugin than it would take to upload the .zip file.

It may be < $1/day but based on how much I would use the one feature it works out to $150/hour if it saves me 2 hours a year.

I'm not saying there aren't others that will get more benefit if they use it more or use more features. I use this single feature when setting up a new site or occasionally to add a plugin to an existing site. I simply can't justify the cost based on my use.

**Comment by Hube2** [comment]
and you've removed updating from private repos. Sorry, but your plugin will not save me more than the cost per year. The cost/benefit is just not there for me to justify continuing to use.

**Comment by afragen** [comment]
I have not removed updating from private repos. That function is still in core. If you're having an issue please see https://git-updater.com/knowledge-base/troubleshooting/

I'm sure we can figure it out.

**Comment by afragen** [comment]
@Hube2 If you're looking to add plugins when setting up a new site. Please take a look at using https://github.com/afragen/wp-dependency-installer

You can see an example here, https://github.com/afragen/group-plugin-installer

**Comment by afragen** [comment]
@Hube2 if you need some help getting something working that should be working, let me know.

**Comment by ezvr** [comment]
afragen I get that you spent a lot of time working on this plugin, but you must realize that the only actually useful feature was the rest fetch from github, not to mention that this plugin barely works most of the time, requiring a lot of reinstalls of the managed plugins and themes.

The price point you set is ridiculous. A shame, and a good way to turn people away. Gone the way of LastPass and the likes. Too greedy.

**Comment by afragen** [comment]
@ezvr how much are you willing to pay per month, per site, for the premium features?

I don't believe we've ever had a conversation regarding something in the plugin not working that I wasn't able to fix, please remind me when that was and what it was about. Thanks.
