### ISSUE TITLE
installation leaves two instances of plugin on dashboard, two folders

### ISSUE THREAD

**Issue by pcoweb** [afragen/git-updater#959]
I updated from 9.x to 10.2.2

Now there are two instances of 10.2.2 showing on my dashboard list of plugins. When I try to activate the first couple of times, I get a series of errors. 

When I look at the folder structure on the site, I find
/wp-content/plugins/git-updater
/wp-content/plugins/github-updater
which seem to be identical.

Please advise on how I should proceed to fix the installation. When I click to activate on one of the plugins, I got some errors the first couple times, but then it worked but I have the two folders and one is listed as non activated. Is it as simple as deleting one of the folders?

I did have the Github updater support plugin activated when I tried the update.

**Comment by afragen** [comment]
Delete the wp-content/plugins/github-updater directory. 

Somehow 2 instances of the plugin have been installed.

**Comment by pcoweb** [comment]
Thanks. That issues seems resolved.
