### ISSUE TITLE
I can not enable gitlab addon 

### ISSUE THREAD

**Issue by nvjacobo** [afragen/git-updater#961]
Hi, 

I can not enable gitlab addon

## Setup 

Git Updater 10.3.2
Git Updater - GitLab 1.0.1
Wordpress 5.7.2

## Description 
I clicked to active gitlab addon. I tested in different installations 

![Screenshot_2021-06-15 Git Updater Settings dev — WordPress(1)](https://user-images.githubusercontent.com/1041987/122123746-fbca0580-cdf3-11eb-93f8-9d40f72c9bcf.png)

But I can not see it in git-updater settings 

![Screenshot_2021-06-15 Git Updater Settings dev — WordPress](https://user-images.githubusercontent.com/1041987/122123435-95dd7e00-cdf3-11eb-9a4d-f4b433c279d2.png)

Thanks, Jacobo

**Comment by afragen** [comment]
You must have a plugin or theme installed that has the `GitLab Plugin URI` or `GitLab Theme URI` to see the GitLab tab.

You can test by downloading and installing this test plugin. https://gitlab.com/afragen/test-gitlab-plugin

**Comment by nvjacobo** [comment]
Thanks! 

It works
