### ISSUE TITLE
Release highlights

### ISSUE THREAD

**Issue by bret-miller** [afragen/git-updater#962]
One thing that annoys me about some projects is that it's very hard to tell what the significance is of each release. This project releases a lot of version with no information about changes. It would be very helpful if you could provide some highlights as to why the release, like:

Fixes blah blah blah blah
Added new setting xxxx
...

Doesn't have be super detailed--just something rather than just a version number. I know I can pull the check-ins to see which files changed, and I do. But without looking at every line of code that changed, it's still often hard to tell what the real changes were for those of us who use the product.

Obviously, just a suggestion. But I'm sure I'm not the only person wondering what changed.

**Comment by afragen** [comment]
Thanks for the feedback. I'll try to do better.
