### ISSUE TITLE
Always shows available update

### ISSUE THREAD

**Issue by jciw** [afragen/git-updater#963]
I have a theme using Git updater, but it always shows an available update, even if the update is the same version number.

I'm using simple version numbers with a single decimal e.g. 1.7 - is this the issue?

**Comment by afragen** [comment]
Can I take a look at the repository in question?

**Comment by jciw** [comment]
Thanks for the quick reply. It's a private repo, but happy to invite if that works?

**Comment by afragen** [comment]
It does. I would only need access for short period of time.

**Comment by jciw** [comment]
Added you to the repo :).

**Comment by afragen** [comment]
I've installed the theme. I decreased the local version number, saw an update, and updated.

I then flushed the cache. I am on version 1.9 and I do not see an update pending.

Can you screenshot what you are seeing?

**Comment by afragen** [comment]
BTW, you only need one `GitHub Theme URI` header.

**Comment by jciw** [comment]
Thanks for looking at this, this is what I get:

![image](https://user-images.githubusercontent.com/80905190/124080052-ce12cc80-da41-11eb-9880-189cf40f99ca.png)

**Comment by afragen** [comment]
What happens after you either _update_ or refresh the cache?

**Comment by jciw** [comment]
Updating keeps the same message in place. Even though the version is higher it will state something like.

You have version 2.0 installed. Update to version 1.9. (note the lower version number).

Clearing cache seems to have solved for now. How often do updated get checked for? i.e how much lag can be expected between pushing on Git and WordPress seeing the update?

**Comment by afragen** [comment]
API calls are cached for 12 hours. You can use the _Refresh Cache_ button in the Settings to force an update.

<img width="538" alt="screenshot_67" src="https://user-images.githubusercontent.com/1296790/124285743-13e39980-db03-11eb-9f70-0de99d19d564.png">

This is what I see currently.

**Comment by jciw** [comment]
Thanks - that clears things up greatly. If you wouldn't mind, please could you remove the screenshot with the client name in place?

**Comment by jciw** [comment]
Hmm, it appears now that even after updating and clearing cache I'm still seeing the update. You have version 2.1 installed. Update to 2.1. Is there anything on the server config that might cause this? The site is using a very minimal amount of plugins, so a conflict there seems unlikely.

**Comment by afragen** [comment]
You might have to clear all your caches, including browser cache.

**Comment by afragen** [comment]
I have 1.9 installed, I will update to 2.1.

Updated to 2.1 successfully, no further update notice. I refreshed cache and still don't see an update notice. This is all expected. It seems I can't replicate your issue. This leads me  to  suspect a server or browser cache issue.

**Comment by jciw** [comment]
Thanks for looking in to this.

Curiously, I assume Git Updater itself updates from Github (or similar) - this doesn't seem to face the same issue.

**Comment by afragen** [comment]
It does update itself from GitHub.

As I've reported, I do not see the same issue that you see.

**Comment by afragen** [comment]
Closing, please reopen if this is still an issue.
