### ISSUE TITLE
[Git Updater]  Git Updater Error Code: 404

### ISSUE THREAD

**Issue by ericp-mrel** [afragen/git-updater#965]
I am getting the following error code when trying to check for updates for one of my private repo plugins which is owned by an organization. I did see the following message in the wiki, but I do not see anyway to be able to generate an access token which belongs to an organization.

> If your private repository is owned by an organization you must obtain a personal access token from the organization, even if you personally have access to the repository.

And a screenshot of the error message from the settings page:

![Screenshot from 2021-08-06 14-43-52](https://user-images.githubusercontent.com/63664924/128563570-77a5bf92-9d5f-48b0-8b97-e50c15ad127a.png)

Is there a way to fix this?

**Comment by ericp-mrel** [comment]
Could part of my problem be the fact that my plugin is organized like this https://github.com/DevinVinson/WordPress-Plugin-Boilerplate where the actual plugin readme.txt and etc is in a subfolder and so Git Updater is unable to find it from the repo API?

**Comment by afragen** [comment]
The main plugin file must be at the root level of the folder.

**Comment by afragen** [comment]
https://git-updater.com/knowledge-base/usage/

**Comment by ericp-mrel** [comment]
Ah, I thought that might be part of it but was deceiving because it was giving me an error about the rate limit.
