### ISSUE TITLE
Unexptected values for ratings and last modified returned

### ISSUE THREAD

**Issue by Zodiac1978** [afragen/git-updater#966]
Hi @afragen and thank you for this great plugin!

I am using this plugin https://github.com/roytanck/rt-plugin-report from @roytanck and I have made this addon for Antispam Bee to add some more custom patterns https://github.com/zodiac1978/custom-patterns-asb with support for Git Updater.

The mentioned plugin (which is also on WordPress.org: https://de.wordpress.org/plugins/plugin-report/) provides a list of values, typically taken from WordPress.org and displays them as a table.

I was irritated that for my custom pattern plugin there is a value returned for "last-modified" of two weeks, although the last release is from February (6-7 months ago). Then I realized the latest commit is from two weeks ago. Would it make sense to switch to releases here or is there a reason why you use the last commit here?

The other unexpected value is the rating. I found your formula:

https://github.com/afragen/git-updater/blob/beaec1539899a5f909663b01dbb1c30719ec8257/src/Git_Updater/API/API.php#L504-L524

But for my custom (mostly unknown) plugin this returns 4% which was very confusing for me the first time I saw it. The problem is, that there is no explanation where this is coming from and how it is calculated.

Is there a way to disable or filter the ratings?

**Comment by afragen** [comment]
I used the commit date for last  updated as not everyone tags releases and I needed something consistent. 

The "rating" is completely arbitrary and is base on stars, issues, and forks. 

https://github.com/afragen/git-updater/blob/5a24d34b52bdd61319fd05d8ad430d0ad950ae7f/src/Git_Updater/API/API.php#L512

I don't believe there's a filter for the rating. It much more of a vanity setting if you repo is popular.

**Comment by afragen** [comment]
I decided to simply remove the star rating. It was only a vanity marker.

https://github.com/afragen/git-updater/commit/b271d132804fc5680521f09e1814ff17a88e4ce5
