### ISSUE TITLE
This repository has not connected to the API or was unable to connect.

### ISSUE THREAD

**Issue by TukuToi** [afragen/git-updater#967]
I added the Git Updater Plugin and inserted/saved my GitHub Token.
I added the header to my plugin `GitHub Plugin URI: https://github.com/TukuToi/tukutoi-contact-form`
I navigated to the Git Updater Settings and there it now says `This repository has not connected to the API or was unable to connect.`

I don't understand what I did wrong.

Does there need to be some specific information on the "remote" repo? 

Appreciate any hint towards a solution, thanks!!

**Comment by TukuToi** [comment]
Nevermind.
It is a new repo, and thus `Primary Branch:    main` was required, as it defaults to `master`

Resolved.

**Comment by riccardodicurti** [comment]
Thanks it was very helpful.
