### ISSUE TITLE
Error when activating own plugin downloaded from Github

### ISSUE THREAD

**Issue by lyonsun** [afragen/git-updater#968]
Hi,

I have developed my own WordPress plugin which is in GitHub repository.

Then I installed Git Updater on the WordPress site and activated it.

Then I downloaded the Source code (zip) file of my own plugin from the releases in GitHub.

Then I installed my own plugin by uploading this zip file in WordPress plugins page.

The installation succeeded, but then when I activate it, it produces many errors: https://ibb.co/j3bwhTr

My understanding is that the plugin was installed in a folder with the tag number: **my-plugin-1.1.0**, rather than a folder just named as **my-plugin**.

Git Updater then can not find my plugin well. But I still would like to ask, is this the expected behaviour? Any suggestion that even if I upload the plugin with a name in this format: **my-plugin-1.1.0** would still work?

Thanks.

Br,
Liang

**Comment by afragen** [comment]
The file path expects the plugin directory name would be **my-plugin** and not **my-plugin-1.1.0**. 

Git Updater will correctly rename this directory if you are using the Git Updater PRO plugin to install your plugin.

What you must do for how you have installed your plugin is to rename the directory to **my-plugin**. Alternatively you could download the zip from GitHub, extract it, rename the container from **my-plugin-1.1.0** to **my-plugin**, zip that, and then install it.

I see where this error occurred and I'll see if I can fix it.

**Comment by afragen** [comment]
This is now fixed in `develop`, https://github.com/afragen/git-updater/commit/08c1bebe74caa795fe77cfda3648413c1a9c27ed https://github.com/afragen/git-updater/commit/428179b777caef6827d85760233ae46e5e08d7d3

Will merge later today.
