### ISSUE TITLE
Requiring pluggable.php too soon breaks other plugins

### ISSUE THREAD

**Issue by fab120** [afragen/git-updater#970]
Requiring `pluggable.php` in [`Bootstrap.php`](https://github.com/afragen/git-updater/blob/cb4d23ac525205058624ac5995601ca335bf043f/src/Git_Updater/Bootstrap.php#L66) breaks all other plugins that are trying to replace functions in that file.

In my case, I'm using `post-smtp` to handle email and it detect that the function `wp_mail` is already defined. This prevent the plugin to do its work.

As [WordPress Codex](https://codex.wordpress.org/Pluggable_Functions) say:
> WordPress loads the built-in functions only if they are undefined **after all plugins have been loaded**.

Loading `pluggable.php` before all other plugins should not be done.

`pluggable.php` is also loaded in [`GU_Trait.php`](https://github.com/afragen/git-updater/blob/b51f2fdd33cdada5fff9201cfce392afa3a19f8a/src/Git_Updater/Traits/GU_Trait.php#L79) but i didn't tested if this file is loaded before any other plugins and it should be verified.

**Comment by afragen** [comment]
Thanks for letting me know I'll get this fixed.

**Comment by afragen** [comment]
Question: Everything in this plugin is loaded in the `plugins_loaded` hook. Look at the main plugin file. Please tell me how this is related then.

**Comment by fab120** [comment]
Bootstrap class is initialized before 'plugins_loaded' action [here](https://github.com/afragen/git-updater/blob/cb4d23ac525205058624ac5995601ca335bf043f/git-updater.php#L47).

Class Boostrap loads `pluggable.php` in the constructor [here](https://github.com/afragen/git-updater/blob/cb4d23ac525205058624ac5995601ca335bf043f/src/Git_Updater/Bootstrap.php#L67);

**Comment by fab120** [comment]
Sorry, I mean [line 50](https://github.com/afragen/git-updater/blob/cb4d23ac525205058624ac5995601ca335bf043f/git-updater.php#L50) in the previous comment. 😅

**Comment by fab120** [comment]
I just dig up trough the code a little bit more.
May I ask you what are you trying to achieve with the `nonce` in Bootstrap class?

A new `nonce` is created in the constructor [here](https://github.com/afragen/git-updater/blob/cb4d23ac525205058624ac5995601ca335bf043f/src/Git_Updater/Bootstrap.php#L69) and assigned to a [static variable](https://github.com/afragen/git-updater/blob/cb4d23ac525205058624ac5995601ca335bf043f/src/Git_Updater/Bootstrap.php#L55).
The function `wp_verify_nonce` is called only in the `rename_on_activation` function [here](https://github.com/afragen/git-updater/blob/cb4d23ac525205058624ac5995601ca335bf043f/src/Git_Updater/Bootstrap.php#L161) and the only place where this function is called is in the [main plugin file](https://github.com/afragen/git-updater/blob/cb4d23ac525205058624ac5995601ca335bf043f/git-updater.php#L50).

To me [this `if`](https://github.com/afragen/git-updater/blob/cb4d23ac525205058624ac5995601ca335bf043f/src/Git_Updater/Bootstrap.php#L161) sounds like:
```php
if (! true) {
   return;
}
```

Always in the same if, is `$this->nonce` correct?
`$nonce` is defined as static so shouldn't it be retrieved with `static::$nonce`?

**Comment by afragen** [comment]
Unfortunately I seem to need to re-create the nonce in several locations. What I'm testing is something like this instead of loading pluggable.php.

```php
		add_action(
			'plugins_loaded',
			function() {
				static::$nonce = wp_create_nonce( 'git-updater' );
			}
		);
```

So far it seems to work.

**Comment by afragen** [comment]
Hotfix, v10.6.1 released. Please let me know if it's fixed.

**Comment by fab120** [comment]
I can confirm that this fixes the problem.

The activation hooks are called after 'plugins_loaded', so `rename_on_activation` shouldn't have any problem to call the `wp_verify_nonce()` function.

Anyway as I said in my [previous comment](https://github.com/afragen/git-updater/issues/970#issuecomment-926638128), I don't understand what the purpose of using the `nonce` in the Bootstrap class.

**Comment by afragen** [comment]
`rename_on_activation()` had a nonce requirement in WPCS.

Thanks for confirming the fix and thanks for reporting. Sorry for the trouble.

**Comment by fab120** [comment]
No problem for the trouble.

Anyway the `nonces` are not supposed to be generated and verified in the same request lifetime.
They are meant to protect against CSRF attacks (and others): you generate the nonce and send it to the user and in the subsequent requests you check if the nonce is present and valid (eg. form submission).

Generating and checking nonce in the same request is like to initialize a variable to `true` and check immediatly after if the variable is still `true`.

You have to verify the `nonce` that the user sends for being sure that the request is valid and not forged.

For example:
```php
// Get request
wp_verify_nonce($_GET['_wpnonce'], 'git-updater');

// Post request
wp_verify_nonce($_POST['_wpnonce'], 'git-updater');

// Or in general
wp_verify_nonce($_REQUEST['_wpnonce'], 'git-updater');
```
([see how WordPress use it internally](https://github.com/WordPress/WordPress/search?p=2&q=wp_verify_nonce))

Specifically to `register_activation_hook`, WordPress already verify the request nonce before calling the activation_hook.

Where can i see WPCS error logs for more details?

Unfortunately the actual usage of `wp_create_nonce` and `wp_verify_nonce` adds nothing to security (at least for Bootstrap class).

**Comment by fab120** [comment]
As you say, WPCS gives you a notice everytime you use $_GET, $_POST, or $_REQUEST.

The check that they do is quite simple and you have to recognize where the error can be suppressed (i think with `// phpcs:ignore WordPress.Security.NonceVerification.Recommended`) or by checking the `nonce`.

In general, any submission from a form that you create must be verified with the nonce (basically in your case any forms under `/wp-admin/options-general.php?page=git-updater`).

Any other case must be analyzed. In the case of activation hook, the nonce is verified by WordPress itself and you are reading `$_GET['plugin']` after that check is already passed. So no risk of CSRF attack in that function and you can safely ignore WPCS error.

The 10.6.0 release has 39 changed files. Next week i can comment some of those changes to help you understand what I would have done.

When it comes to security, always ask for a second opinion.. I'm sure what I'm telling you but I'm still human.  😅

**Comment by afragen** [comment]
I just received a email from the plugins team about similar issues in another plugin. I decided to remove all the `// phpcs:ingore ...` and fix them.

Unfortunately I'm only a one man show so not really anyone I can tag for a security audit.

I appreciate whatever comments you have. Thanks.

**Comment by afragen** [comment]
I believe I've fixed all the nonces correctly in the develop branch.

**Comment by fab120** [comment]
I just looked at the diff for the last 9 commits on the develop branch and the approach is correct.
You removed every `static::$nonce` and used `wp_verify_nonce` with parameters from submitted forms.

> it's a combination of ignoring the known and verifying the unknown

Yes, that's the right mood! 😂
