### ISSUE TITLE
Notices in Admin with custom wp-content directory

### ISSUE THREAD

**Issue by hirasso** [afragen/git-updater#971]
Hi there! There is a problem with the current version of git updater. When using a custom WordPress folder structure, this line in `Plugin.php` doesn't match anything, which in turn leads to quite a few `undefined offset` notices:

```php
// Plugin.php,  line 200
preg_match( '/\/wp-content.*/', $git_plugin['local_path'], $matches );
```
...because in my setup the `wp-content` folder is called `content`:
```php
// wp-config.php
define('WP_CONTENT_URL', WP_HOME . '/content');
define('WP_CONTENT_DIR', dirname(__FILE__) . '/content');
```
A quick fix would be:
```php
$wp_content_dir = basename(WP_CONTENT_DIR);
preg_match( "/\/$wp_content_dir.*/", $git_plugin['local_path'], $matches );
```

**Comment by afragen** [comment]
Is there some reason you're using a non-standard directory structure?

**Comment by afragen** [comment]
I have to think about it. Not sure where else I reference "wp-content" but changing all of those to non-standard locations might be unnecessarily difficult.
