### ISSUE TITLE
Deprecation of Atlassian account password for Bitbucket API and Git activity

### ISSUE THREAD

**Issue by DaWoblefet** [afragen/git-updater#973]
Atlassian recently sent out an email message that may be relevant for this plugin: https://bitbucket.org/blog/deprecating-atlassian-account-password-for-bitbucket-api-and-git-activity. Apparently new users will be affected September 13, and existing users will be affected March 1, 2022.

I'm not actually too sure whether or not this change will affect Git Updater, but I wanted to pass it along in case you see reports of issues with Bitbucket post-September 13.

**Comment by afragen** [comment]
I appreciate the heads up. I already have documentation for that.

https://git-updater.com/knowledge-base/settings/#articleTOC_4
