### ISSUE TITLE
PHP warning updating translations

### ISSUE THREAD

**Issue by ArtGoddess** [afragen/git-updater#974]
Hello,

After installing the plugin in a self-hosted WordPress site using es-ES language, translations have been retrieved. At this point, this PHP warning can be seen:

```
Actualizando las traducciones de Git Updater (es_ES)…
Warning: Undefined variable $releases in /home/user/domain.com/wp-content/plugins/git-updater/src/Git_Updater/Traits/Basic_Auth_Loader.php on line 269
```

I think the translation has been applied.

My set up: PHP 8 in Apache server, WordPress 5.8.2, git-updater-10.6.7.

Many thanks!

**Comment by afragen** [comment]
This is fixed in the develop branch. I'll try to release it tonight. 

It shouldn't caused any issues.
