### ISSUE TITLE
Git Updater Error Code: 404

### ISSUE THREAD

**Issue by atanemani** [afragen/git-updater#976]
Hi Andy.
I recently used GU plugin for a website and I got this errors :
`Git Updater Error Code: 404
GitHub API’s rate limit will reset in 34 minutes.
It looks like you are running into GitHub API rate limits. Be sure and configure a Personal Access Token to avoid this issue`
`Git Updater Error Code: 404
There is probably an access token or password error on the Git Updater Settings page`
I checked everything but still my problem not fixed.

**Comment by afragen** [comment]
As the notice says you need to set a personal access token to avoid GitHub rate limiting your IP. 

https://git-updater.com/knowledge-base/general-usage/#articleTOC_0

**Comment by atanemani** [comment]
I set a personal access token, but still not work.

**Comment by afragen** [comment]
Send screenshot of GitHub tab.

What privileges did you give token?

**Comment by atanemani** [comment]
![Firefox_Screenshot_2021-12-22T05-35-52 606Z](https://user-images.githubusercontent.com/77187507/147041064-c4b95305-6edb-47bf-a3bc-b411ea0b7c7b.png)
repo, read packages

**Comment by afragen** [comment]
If all the private repos are yours you don't need to add a token for each one, just a token in the GitHub.com token space.

You should have the correct privileges. Try using the refresh cache button. 
Take a look at https://git-updater.com/knowledge-base/troubleshooting/

**Comment by atanemani** [comment]
Hello again.
The 404 error was because difference in name of my compare plugin and API errors was because theme and plugins version which was 0.0.0, and all of my errors solved.
Thank you very much Andy.
