### ISSUE TITLE
Getting hammered with continuous "API rate limit exceeded" 403 error

### ISSUE THREAD

**Issue by MSEGitHub** [afragen/git-updater#980]
I realize no one else seems to be complaining about this so it must be something unique to me?
![Screenshot 2022-01-17 123039](https://user-images.githubusercontent.com/63716480/149815006-9eafffcf-d0c9-4ef9-93df-d6e2542c8da4.png)

This problem started for me a few months ago. They are all private repositories and I do have a "newly" generated personal access token. I reached out to GitHub support and this is the list they gave me for top URL's of the last 24 hours:

`
url count   percent
`
`
https://api.github.com/repos/mystudioengine/the-events-calendar/contents/readme.txt?ref=%5BFILTERED%5D  42082   31.479653
https://api.github.com/repos/mystudioengine/event-tickets/contents/readme.txt?ref=%5BFILTERED%5D    42032   31.442250
https://api.github.com/repos/afragen/git-updater/contents/CHANGES.md?ref=%5BFILTERED%5D 13278   9.932675
https://api.github.com/repos/afragen/git-updater/contents/readme.txt?ref=%5BFILTERED%5D 13251   9.912478
https://api.github.com/repos/afragen/git-updater/tags   4006    2.996709
https://api.github.com/repos/mystudioengine/event-tickets/tags  2404    1.798324
https://api.github.com/repos/mystudioengine/the-events-calendar/tags    2328    1.741472
https://api.github.com/repos/afragen/the-events-calendar-category-colors/tags   1310    0.979952
`

When it is locked out I do get the following in query monitor:
![HTTP Console](https://user-images.githubusercontent.com/63716480/149814992-9a959f27-26be-4e95-b042-e8d4a6eaf5ad.png)

Any ideas on what could be causing this?

**Comment by afragen** [comment]
Have you set a GitHub personal access token in the settings?

Unauthenticated API calls have a limit of 60 / hr. Authenticated gets you 5000/hr

I do have code cache and those so you don't continue to make API calls until clear.

**Comment by MSEGitHub** [comment]
Yes, I have one of the "updated" personal access tokens set in the settings.

**Comment by afragen** [comment]
This is what I see from the command line. 

`$ curl -I --header "Authorization: token ghp_xxxxxxxxxxxx" https://api.github.com/repos/afragen/git-Updater`

```HTTP/2 200 
server: GitHub.com
date: Thu, 09 Dec 2021 19:02:27 GMT
content-type: application/json; charset=utf-8
content-length: 6030
cache-control: private, max-age=60, s-maxage=60
vary: Accept, Authorization, Cookie, X-GitHub-OTP
etag: "afddf09c06b746b811ceaf40c11e35adcb2c9a4af3c732bd9d50b3a00924d295"
last-modified: Thu, 09 Dec 2021 17:59:42 GMT
x-oauth-scopes: repo, workflow
x-accepted-oauth-scopes: repo
x-github-media-type: github.v3; format=json
x-ratelimit-limit: 5000
x-ratelimit-remaining: 4968
x-ratelimit-reset: 1639077066
x-ratelimit-used: 32
x-ratelimit-resource: core
access-control-expose-headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset
access-control-allow-origin: *
strict-transport-security: max-age=31536000; includeSubdomains; preload
x-frame-options: deny
x-content-type-options: nosniff
x-xss-protection: 0
referrer-policy: origin-when-cross-origin, strict-origin-when-cross-origin
content-security-policy: default-src 'none'
vary: Accept-Encoding, Accept, X-Requested-With
x-github-request-id: D1F6:771B:97CD9:1A2E5E:61B252C3```

Specifically the x-ratelimit headers

**Comment by MSEGitHub** [comment]
Here's what I get:

curl -I --header "Authorization: token ghp_xxxxxxxxxxxxxxxxxxxxxxxx" https://api.github.com/repos/mystudioengine
HTTP/1.1 403 Forbidden
Server: GitHub.com
Date: Mon, 17 Jan 2022 22:24:39 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 169
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 0
X-RateLimit-Reset: 1642460597
X-RateLimit-Used: 5000
X-RateLimit-Resource: core
X-OAuth-Scopes: read:packages, repo, workflow
X-Accepted-OAuth-Scopes: repo
X-GitHub-Media-Type: github.v3; format=json
Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset
Access-Control-Allow-Origin: *
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: deny
X-Content-Type-Options: nosniff
X-XSS-Protection: 0
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
Content-Security-Policy: default-src 'none'
Vary: Accept-Encoding, Accept, X-Requested-With
X-GitHub-Request-Id: C92F:3707:1AED8A9:32F4F26:61E5ECA7

**Comment by afragen** [comment]
We'll you have an access token but you've hit the rate limit and will need to wait.

**Comment by afragen** [comment]
It would seem that you're access token is correct. Perhaps an copy/paste error into the Settings?

**Comment by afragen** [comment]
It would seem that you're access token is correct. Perhaps an copy/paste error into the Settings?

If you go to the main settings and check to bypass WP-Cron you will see if there are new errors in Query Monitor.

**Comment by MSEGitHub** [comment]
I suppose there could always be a chance the token is wrong but I have been using the key a while and when the count resets everything works as it should.

![image](https://user-images.githubusercontent.com/63716480/149861442-190a4a2c-9989-46a7-baf2-8f55778ce15f.png)

I enabled WP-Cron bypass on one site and didn't see any new/different errors in QM. Do I need to change that settings on all of our sites?

**Comment by afragen** [comment]
You shouldn't. I only use that setting for troubleshooting. 

I guess it's possible it GitHub is having an issue but it's strange. Obviously difficult to pin down too.

**Comment by MSEGitHub** [comment]
So I tried a different access token but that didn't help. But let me ask you a question.

I created a new token under a different user and only added it to my local VM. Every time I ran this command I would lose one hit (which I would expect). 
`curl -I --header "Authorization: token ghp_xxxxxxxxxxxxxxxxxx" https://api.github.com/repos/mystudioengine/msechild`

However, whenever I would load/refresh a page on either the frontend or backend of the site I would lose an average of 5/6 hits each time. Is this normal?

**Comment by afragen** [comment]
If you turn off WP-Cron background updating you might have a better idea, from Query Monitor, what API calls are being run and why they might be failing.

**Comment by MSEGitHub** [comment]
With WP-Cron background disabled, on every page load I see these three calls:

![image](https://user-images.githubusercontent.com/63716480/150325503-ed138fbc-1644-487b-821b-f814b313dc0f.png)

**Comment by MSEGitHub** [comment]
So I checked this on two hosted sites we have and had basically the same results. One site had the plugin disabled and everything was fine until I forced a cache refresh, then I had this on every page load:
![image](https://user-images.githubusercontent.com/63716480/150332049-81e72173-6562-4eb8-8eb0-dda907dcfbf2.png)

The other site already had the plugin running and I get this on every page load:
![image](https://user-images.githubusercontent.com/63716480/150332152-05cefeb3-f2f5-4107-a32c-ff5ffce26f90.png)

**Comment by afragen** [comment]
What kind of caching do you have on the site? It's almost as if the results are not able to be cached by Git Updater into the WP database.

**Comment by MSEGitHub** [comment]
We use WP-Rocket for caching on the hosted sites (not on my local VM). But now that you mention caching, we use Divi as a theme and they recently added their own caching (I tried disabling the Divi caching on my local VM but it did not appear to make a difference).

**Comment by afragen** [comment]
See if disabling any/all of your caches has any effect.

**Comment by afragen** [comment]
I haven't asked but are you using the current version of Git Updater?

**Comment by afragen** [comment]
On your local VM is it working correctly now?

**Comment by MSEGitHub** [comment]
Yes, I am running the current version of Git Updater. My local VM still has the same three connections as earlier:
![image](https://user-images.githubusercontent.com/63716480/150370371-69b1c874-f1ab-48db-84ab-706776d35f4c.png)

**Comment by afragen** [comment]
Let's work with to local VM and see if we can figure this out. 

Git Updater is designed to cache an API response for 12 hrs. It uses the WP options table. 

Can you describe your local VM?

**Comment by MSEGitHub** [comment]
Sure, anything in particular you want to know?

It's a windows VM running WAMP
Apache 2.4.46
WordPress 5.8.3 (512M mem)
PHP 7.4.9
MySQL 5.7.31

The major plugins are all the Events Calendar plugins, assorted WooCommerce plugins, ACF, Gravity Forms and the Divi theme.
I did also try disabling all the plugins and changing the theme but it had no effect.

**Comment by afragen** [comment]
It sure seems like there's some off issue where the API response data is not being saved into the options table using the update_site_option() command. 

https://github.com/afragen/git-updater/blob/7d2da1edbc6d2c1e0d4e8254c0f98ac090ae3640/src/Git_Updater/Traits/GU_Trait.php#L122

**Comment by MSEGitHub** [comment]
I currently have 24 entries in my options table (one for each plugin) and they all have a timeout for tomorrow morning.
Is that correct or should there be a different amount?

**Comment by afragen** [comment]
So each API bit is written to a single repository data object. As new data gets stored the timeout changes. The problem seems to be the the 'tags' data gets a valid response but doesn't seem to be stored. If it's not stored it will appear as if it needs to be polled again. Generating new and more API calls.

**Comment by afragen** [comment]
The data entry should all have the same number of data points.

**Comment by MSEGitHub** [comment]
So I think I found the problem. It doesn't like the data being saved. It appears to fail if there are emoticons in the readme or changes. I fixed my other two repos but In the git-updater changes file there are various icons like below:

![image](https://user-images.githubusercontent.com/63716480/150551871-214aaa4f-c254-40e3-a88c-372ba1f38b62.png)

**Comment by chesio** [comment]
> So I think I found the problem. It doesn't like the data being saved.

@MSEGitHub Have a look at the database charset your WordPress installation use: when there are problems with emojis, it's often due `utf8` being used instead of `utf8mb4`.

**Comment by afragen** [comment]
As @chesio said that's probably an issue with the database charset. 

You should be able to check this in the Tools > Site Health menu.

**Comment by afragen** [comment]
The solution might be to export and the database, create a new one and then import the old data.

**Comment by MSEGitHub** [comment]
@chesio & @afragen thanks for the info. Actually the wp_config and the site health both say "utf8mb4" but when I check the database directly it shows the core tables as "utf8".

I found a script that would upgrade the tables in place so we'll see how that goes. Either way, thanks for the help. I'm glad this problem is solved.
