### ISSUE TITLE
Crashes on Theme page with Uncaught ArgumentCountError

### ISSUE THREAD

**Issue by mcguffin** [afragen/git-updater#981]
**Error message:**
```
Uncaught ArgumentCountError: 5 arguments are required, 4 given in [REDACTED]/wp-content/plugins/git-updater/src/Git_Updater/Theme.php:534
Stack trace:
#0 [REDACTED]/wp-content/plugins/git-updater/src/Git_Updater/Theme.php(534): printf('Zeige Details d...', '1.4.14', '', '
```

**Environment:**
 - PHP 8
 - WordPress 5.8.3
 - Git Updater 10.6.12
 - Git Updater - Bitbucket 1.2.0

Any fix very appreciated!

**Comment by afragen** [comment]
Can you tell the steps to reproduce this?

**Comment by afragen** [comment]
That particular bit of referenced code hasn't changed in a long time.

**Comment by mcguffin** [comment]
I think I found the cause. It's in the translations:
https://github.com/afragen/git-updater-translations/blob/master/languages/git-updater-de_DE.po#L496-L497
The german string has 4 placeholders instead of 3.
I think PHP 8 made this a fatal error…

(BTW: Your lightspeed response is very much appreciated!)

**Comment by mcguffin** [comment]
After switching the backend language of my user to `en_US` everything works well again.

**Comment by afragen** [comment]
Oops. I guess the translator wasn't paying close enough attention. I do love them though. 

I'll get it fixed. Thanks for the PR. I hope to have it fixed soon. I need to get back to a keyboard.
