### ISSUE TITLE
Update to old version

### ISSUE THREAD

**Issue by hupe13** [afragen/git-updater#982]
I used the git-updater for https://github.com/hupe13/extensions-leaflet-map-github to version 1.4. Then I didn't use the git-updater, so I deleted the line "* GitHub Plugin URI:". But now I would like to use the git-updater again and I have added the line "* GitHub Plugin URI:" . In between I changed the slug from extensions-leaflet-map to extensions-leaflet-map-github.
The display for an update to a new version is always correct. But when I update to the new version, the old version 1.4 will be installed. 
I tried different settings:

* played with version information. 
* renamed extensions-leaflet-map.php to extensions-leaflet-map-github.php
* created a  new release. 

The relevant version information is in the extensions-leaflet-map.php, not in the readme, right? Is it necessary to always create a release? What should I do?

Thank you.

**Comment by afragen** [comment]
Hi. Is there a question?

**Comment by hupe13** [comment]
I would like to get the new version, not the very old (1.4) one.
As I wrote, it detects that there is a new version (2.2.4.24) and it shows correctly when I click on details, but when I update, it installs the very old version 1.4. This is not correct.

**Comment by hupe13** [comment]
Ok, I found a possible cause. I tagged badly. If I give a `git tag` command, version 1.4 appears as first:
```
> git tag
1.4
V2.0
V2.0.1
```
Tags should be sorted by creation date:
```
> git tag --sort=-creatordate 
v2.2.4.23
V2.2.3
V2.2.2
V2.2
```

**Comment by afragen** [comment]
Creation date of the tag is not something that the API returns.

**Comment by hupe13** [comment]
Thank you very much. I moved the last tag to semantic versioning, now it works. Thank you.
