### ISSUE TITLE
Git Updater Error: Combined Query (wp-combined-queries:master) - Not Found

### ISSUE THREAD

**Issue by therealgilles** [afragen/git-updater#983]
I keep seeing this error in my debug.log file: `Git Updater Error: Combined Query (wp-combined-queries:master) - Not Found`
I added the code below to try to disable it but to no avail:

```PHP
add_action(
  'plugins_loaded',
  function() {
    if ( class_exists( 'Fragen\Git_Updater\Ignore' ) ) {
      new Fragen\Git_Updater\Ignore( 'wp-combined-queries', 'wp-combine-queries/combined-query.php' );
    }
  }
);
```

What should I do?

**Comment by afragen** [comment]
That error implies a 404 error when checking the API. If it's a private repo it means the access token could be wrong. 

If it's a public repo it usually means the default branch is not `master` and the repo needs a `Primary Branch` header. 

https://git-updater.com/knowledge-base/required-headers/#articleTOC_0

**Comment by afragen** [comment]
If you Ignore the plugin it will never check for updates.

**Comment by afragen** [comment]
Some screenshots of the GitHub tab might be helpful. Also, are there any HTTP errors in Query Monitor?

https://git-updater.com/knowledge-base/troubleshooting/

**Comment by therealgilles** [comment]
@afragen: Thank you for the replies. It turns out the plugin had an outdated URI in its header.
Still I was not able to make the ignore statement work. What did I do wrong there? I'm pretty sure I got the file path correct. The documentation references a plugin 'slug' but I am not sure how you define it.

**Comment by afragen** [comment]
Can you post a screenshot of your Git Updater > GitHub page?

it's possible that the `Ignore` is working but you've hit upon a cached value. `Refresh Cache` may resolve this.

**Comment by therealgilles** [comment]
hmm is it possible that I cannot use plugins_loaded in my functions.php file? I think that's the problem I'm running into. It can only be used in plugins.

**Comment by therealgilles** [comment]
Yes understood. It may be useful to others to add a note that the plugins_loaded hook won't work in a theme functions.php.

**Comment by afragen** [comment]
It probably safer to use a single purpose plugin for this. It will continue to work regardless of the theme and it's presence let's you know why it's there.

**Comment by afragen** [comment]
If everything is working, please close this issue. Thanks.
