### ISSUE TITLE
Plugin icons not behaving as expected

### ISSUE THREAD

**Issue by pedro-mendonca** [afragen/git-updater#984]
If a plugin hosted on GitHub has `/assets/` `icon-[128x128|256x256].jpg` or `icon.svg` all works as expected.

But for `icon-[128x128|256x256].png` it's not.

The [foreach](https://github.com/afragen/git-updater/blob/develop/src/Git_Updater/Plugin.php#L218) always checks for `.jpg` last, and sets to null if none found, even if there was a `.png` found in the previous loop.

The solution is to only set the array key if the file is found.

@afragen does it need an array key with `null` value if no icon is found?

**Comment by afragen** [comment]
Fixed in 45ef89735605755c74cd91db1a2a29c522e3db43
