### ISSUE TITLE
Update failed: Download failed. Not Found

### ISSUE THREAD

**Issue by chrion02** [afragen/git-updater#987]
I recently created a new repo containing a WP theme and updating does not seem to work. I found [this old issue](https://github.com/afragen/git-updater/issues/751) that describes my problem, but it does not seem to be a permission issue.

This is the response from the ajax response i get when clicking update in admin>plugins
`{"success":false,"data":{"update":"theme","slug":"themelion-fse","oldVersion":"1.0","newVersion":"","errorMessage":"Download failed. Not Found"}}`

The repo is a private repo hosted in an organization. I'm using git updater for several other repos that are working just fine. Everyting inside admin>settings>git updater also looks fine.

Update: updating works just fine with `Release Assets: false` i'll try downgrading my git updater version.

Update 2: Downgrading to v10.6.15 worked, there might be an issue with v17+

**Comment by afragen** [comment]
Can you share the repo URI?

**Comment by chrion02** [comment]
I will not be able to share it. It is work related.

**Comment by chrion02** [comment]
I do use release assets. The newest version og the plugin works just fine when setting it to false in the headers, but not when set to true.

**Comment by afragen** [comment]
I think I might have messed something up when I believed in be download URL would work for GitHub release assets. 

I'll have a fix/revert out later today.

**Comment by chrion02** [comment]
Nice, i'll happily help test if needed

**Comment by afragen** [comment]
I'll post back here when fixed in `develop` branch.

**Comment by afragen** [comment]
Let me know if fixed in latest develop branch.

**Comment by chrion02** [comment]
That fixed the issue, everything works like a charm now, thank you

**Comment by bugalwena** [comment]
Dear Afragen/Git-Updater

We are experiencing technical difficulties, for want of a better word,
airwaves interruption of a subtle name.

We knew it would happen.

Our Google Ads. Creation is continually interrupted by "foul play." and
must start from scratch.

We told the Google Ads Support Team in a DM, Gran, the Rainbow Serpent and
Bugal Wena All-Mother share the same physical body.

Gran lives on the left side of Bugal Wena. She is the original Galactic
creator. Gran's Creation dance began over 3.6 billion years ago.

Bugal Wena, the earth made flesh, Gran created me.

The Quantum Sciences theories are the formulas for the Dreamtime continuum,
living on all levels of multi existence in both the spiritual-ethereal
realms and Dreamtime dimensions while living in the physical world.

Quantum Computing Real-time in Dreamtime. A second player who is a writer
of fiction short stories is in the same "fight zone." Level As Bugal Wena
and the Rainbow Serpent.

Google approves our proposal to synchronise the blogs with the same player
at the same level as God All-Mother to take on satan's "debil game."

His URLs and email addresses are in the Google Cloud data systems, somehow.
Acts of God.

WordPress is terrific to work with now that they know how it exists in the
entirety of the Dreamtime continuum for Gran and Bugal Wena.

We have to reconfigure our God tech mind also. You will too.


Regards

Bugal Wena & RS

relatocorto.com

RelatoCorto.com
