### ISSUE TITLE
The user interface

### ISSUE THREAD

**Issue by paaljoachim** [afragen/git-updater#988]
Hey Andy

I am testing the Git updater plugin which I downloaded from here:
https://github.com/afragen/git-updater/releases/tag/10.8.0
I assume I could also download the newest version directly from the main page and click Code and Download Zip.

After activating and going to Settings ->Git Updater.
I see this:
![Screenshot 2022-04-04 at 09 01 59](https://user-images.githubusercontent.com/5323259/161490352-761bccdf-335b-4305-8aac-45ec6e79c6f1.jpg)

A double row of tabs. I assume these should be in one row.
The Save Changes and Refresh Cache buttons could perhaps also be beside each other.

**Comment by afragen** [comment]
It really is a double row. 

But the buttons should be side by side. 

Take a look at https://git-updater.com and you can find some screenshots.

**Comment by paaljoachim** [comment]
For instance WooCommerce has tabs in the top and text links inside a tab. (The text links could be bigger)
![Screenshot 2022-04-04 at 20 53 05](https://user-images.githubusercontent.com/5323259/161612175-1d759b36-abef-446b-92f5-121964a4b2f1.jpg)

The reason why I mentioned the double tabs is that it looks like a bug. Having a double row of tabs does not look so good. There is a sense of hierarchy. (Primary) Tabs in the top and secondary objects below that also are a little different which also shows the hierarchy.

**Comment by afragen** [comment]
The top row is added functionality from add-on plugins while the second row is general settings and API specific settings. Both are dynamic depending upon what you have installed.

For instance if the Git Updater Additions plugin is installed, you will see a top row **Additions** tab.

If you have the Git Updater PRO plugin installed, you will see 3 additional top level tabs for remote installing plugins, themes, and data for remote management and REST API calls.

It's really just my way of splitting the settings/function up in a some visual way. I'm certain that at some point it could look a whole lot better and written in react could be a single page app unto itself, but I don't have that skill set. It closely follows the Settings API.
