### ISSUE TITLE
Fatal error after update

### ISSUE THREAD

**Issue by BWBama85** [afragen/git-updater#990]
```
[24-Apr-2022 16:29:15 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Fragen\Git_Updater\move_dir() in /home/nginx/domains/bamapolitics.com/public/wp-content/plugins/git-updater/src/Git_Updater/Base.php:527
Stack trace:
#0 /home/nginx/domains/bamapolitics.com/public/wp-includes/class-wp-hook.php(307): Fragen\Git_Updater\Base->upgrader_source_selection()
#1 /home/nginx/domains/bamapolitics.com/public/wp-includes/plugin.php(189): WP_Hook->apply_filters()
#2 /home/nginx/domains/bamapolitics.com/public/wp-admin/includes/class-wp-upgrader.php(527): apply_filters()
#3 /home/nginx/domains/bamapolitics.com/public/wp-admin/includes/class-wp-upgrader.php(798): WP_Upgrader->install_package()
#4 /home/nginx/domains/bamapolitics.com/public/wp-admin/includes/class-plugin-upgrader.php(345): WP_Upgrader->run()
#5 /home/nginx/domains/bamapolitics.com/public/wp-admin/update.php(51): Plugin_Upgrader->bulk_upgrade()
#6 {main}
  thrown in /home/nginx/domains/bamapolitics.com/public/wp-content/plugins/git-updater/src/Git_Updater/Base.php on line 527
```

**Comment by afragen** [comment]
Not sure why this works for me and not for you. Can you change line 526 in Base.php from `new Shim();` to `require_once __DIR__ '/Shim.php';` or switch to the `develop` branch and test?

**Comment by BWBama85** [comment]
Now I get this:

`[25-Apr-2022 01:27:34 UTC] PHP Fatal error:  Cannot declare class Fragen\Git_Updater\Shim, because the name is already in use in /home/nginx/domains/bamapolitics.com/public/wp-content/plugins/git-updater/src/Git_Updater/Shim.php on line 19`

**Comment by afragen** [comment]
I don't know why initializing the class using new Shim() didn't work for you. 

What other Git Updater plugin do you have installed?

I think I know the issue and I may need to get some of the other plugins updated first.

**Comment by afragen** [comment]
Also what version of PHP are you using?

**Comment by BWBama85** [comment]
I am using PHP 8.1.5. I also am doing a trial of the pro version of the plugin so I have that installed as well.

**Comment by afragen** [comment]
I'll have an update to the PRO version too. You'll need to update both.

**Comment by afragen** [comment]
Update Git Updater PRO and it should work. I'm updating Git Updater a bit more slowly as all the other Git Updater plugins will likely need to be updated first.

**Comment by afragen** [comment]
Please let me know if this is fixed.

**Comment by BWBama85** [comment]
Updated Pro and everything seems to work fine now. Was able to update my plugin without issue.
