### ISSUE TITLE
Git-updater HTTP requests being made on other admin screens

### ISSUE THREAD

**Issue by therealgilles** [afragen/git-updater#991]
Is there a reason there are git-updater requests on other plugin admin screens?
For instance, I see this one:
    /wp-content/plugins/git-updater/vendor/afragen/wp-dismiss-notice/js/dismiss-notice.js

I also see requests to api.github.com for the plugins handled by git-updater.
Is there a reason why the dismiss notice is always there and why plugin checks are not handled through wp-cron events instead?

Plugins should not run on other plugin admin screens (in my opinion). It makes the backend slower for no good reason.

**Comment by afragen** [comment]
That comes from a composer library, yes I did write the library. Let me see if I can modify it's loading better.

**Comment by afragen** [comment]
Please realize this is only a 40 line JS file.

**Comment by therealgilles** [comment]
@afragen: Sure. But I'm more worried about the unnecessary HTTP request to get the JS file. If many of the plugins do this, it adds up to seconds of wasted time every time the admin screens load.

What about the api.github.com plugin checks? I'm actually more worried about these.

**Comment by afragen** [comment]
I think it can simply remove the call to load it entirely as it should load from the autoloader when needed. 

If you want to check, comment out https://github.com/afragen/git-updater/blob/5abfc117f6c1ffd3ba8afa00c3962c8e90013a39/src/Git_Updater/Bootstrap.php#L96

**Comment by afragen** [comment]
This should limit the HTTP check to weekly. https://github.com/afragen/git-updater/commit/cc1aebaf23af32ec406d74e735056d039cf2476b

**Comment by therealgilles** [comment]
@afragen: Really appreciate your making changes to improve the plugin :)

**Comment by afragen** [comment]
Actually the changes ended up being in the `wp-dismiss-notice` library. Makes for improving all plugins that use it.
