### ISSUE TITLE
Gitlab Tab not showing

### ISSUE THREAD

**Issue by pa2codes** [afragen/git-updater#993]
Hi all,

I have installed latest git-updater, then GitLab Addon via the settings page.

However even after running the cronjob there is no "Gitlab" Tab, only a field within the github section.
I tried to put the Personal Access Token in there, but nothing happens. I checked the bypass option, ran wp-cron manually, I waited for a hour, reinstalled...nothing worked.

Any ideas?

Thanks!

<img width="785" alt="image" src="https://user-images.githubusercontent.com/62615295/170652943-292a5b7f-860e-462b-bc23-0a54bf28c1ae.png">

**Comment by afragen** [comment]
You don't need to enter a personal access token for `Git Updater - GitLab`. 

The GitLab tab is dynamic if you have a plugin or theme with the appropriate header. 

https://git-updater.com/knowledge-base/usage/#articleTOC_5

**Comment by pa2codes** [comment]
Hi @afragen ,

Thanks for your fast reply. My mistake was to not specify the main branch, because master is your plugins default.

Sorry! and thanks for your fast support.
