### ISSUE TITLE
Add `Tested up to: x.x` to `README.txt`

### ISSUE THREAD

**Issue by grandeljay** [afragen/git-updater#994]
I couldn't find any official documentation mentioning it but it seems to be used and supported everywhere.

![image](https://user-images.githubusercontent.com/45571053/171615417-4f3b95ee-2cfd-4abb-957d-e2ff31d2fe2e.png)

**Comment by afragen** [comment]
While this is not required for plugins not hosted in dot org I do have he following, https://github.com/afragen/git-updater/blob/df1115e38257c5d27ccc2d671f42dec5369102b4/readme.txt#L8

`trunk` is the bleeding edge nightly of WordPress core and is what I use daily for development and testing.

**Comment by grandeljay** [comment]
The `Tested up to` is supposed to make life easer for users/maintainers IMO and I don't consider this a good solution. 

Don't you think it's a bit complicated to have to look up a plugins source code in order to see if it's compatible? Now I know you always test the WP trunk but the next user might not.

**Comment by afragen** [comment]
I'll see about keeping that up to date with the next release. 

Thanks.
