### ISSUE TITLE
"Install Plugin" menu missing

### ISSUE THREAD

**Issue by therealgilles** [afragen/git-updater#996]
Hi @afragen, I think I asked you about this before but somehow cannot remember how it was resolved. The "Install Plugin" menu does not show. Here is what I see:

<img width="372" alt="Screenshot 2022-07-31 at 11 24 56 PM" src="https://user-images.githubusercontent.com/18076992/182085357-51743d36-d10c-4f7e-8efb-db80c2e323c2.png">

Do you recall what the fix was by any chance?

**Comment by afragen** [comment]
This is now a premium feature in the Git Updater PRO plugin.

**Comment by therealgilles** [comment]
Is there a non-premium way of installing plugins and themes then?

**Comment by afragen** [comment]
Using the Core Add Plugin or Add Theme menu. Just have a zip file of what you want to install locally.

**Comment by afragen** [comment]
It's only $3 a month for a single site and as many local environments as you need. 

https://git-updater.com/git-updater-pro/

**Comment by therealgilles** [comment]
Thanks for the reminder. I have donated before and will make another donation. I prefer that to a monthly subscription.
