### ISSUE TITLE
Version 11.0.4 implicitly requires PHP 8

### ISSUE THREAD

**Issue by chesio** [afragen/git-updater#998]
Hi Andy,

with an update to the latest version of [afragen/wordpress-plugin-readme-parser](https://github.com/afragen/wordpress-plugin-readme-parser) in [this commit](https://github.com/afragen/git-updater/commit/79d47cd51a7a9f540ccee38f50a03b082c0643ed) Git Updater implicitly requires PHP 8 due to use of PHP-8-only functions [`str_contains`](https://www.php.net/manual/en/function.str-contains.php) and [`str_starts_with`](https://www.php.net/manual/en/function.str-starts-with.php) - see [this line](https://github.com/afragen/wordpress-plugin-readme-parser/blob/master/class-parser.php#L245).

I assume this was by mistake, thus this heads up.

**Comment by chesio** [comment]
Alternative solution would be to require WordPress 5.9 or newer as both functions have polyfills added in WP 5.9, see: https://core.trac.wordpress.org/ticket/49652 and https://core.trac.wordpress.org/ticket/54377

**Comment by afragen** [comment]
Looks like I'll need to require WP 5.9 then. I don't write the readme parser, I just use it.

Thanks for letting me know.
