### ISSUE TITLE
"Call to undefined function Fragen\Git_Updater\move_dir() ..."

### ISSUE THREAD

**Issue by Mierscheid** [afragen/git-updater#999]
Hi Folks!

WP 6.0.2
PHP 8.1.9

When I try to activate the (Master or Developer) plugin, the following error occurs:

Fatal error: Uncaught Error: Call to undefined function Fragen\Git_Updater\move_dir() in /var/www/vhosts/XXXXXXX.web3.alfahosting-server.de/httpdocs/XXXXXXXX.XX/wp-content/plugins/git-updater-master/src/Git_Updater/Bootstrap.php:163 Stack trace: #0 /var/www/vhosts/XXXXXXXX.web3.alfahosting-server.de/httpdocs/XXXXXXXXX.XX/wp-includes/class-wp-hook.php(307): Fragen\Git_Updater\Bootstrap->rename_on_activation('') #1 /var/www/vhosts/XXXXXXXXXX.web3.alfahosting-server.de/httpdocs/hessburg.de/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array) #2 /var/www/vhosts/XXXXXXXXXX.web3.alfahosting-server.de/httpdocs/XXXXXXXX.XX/wp-includes/plugin.php(476): WP_Hook->do_action(Array) #3 /var/www/vhosts/XXXXXXXX.web3.alfahosting-server.de/httpdocs/XXXXXXXX.XX/wp-admin/plugins.php(194): do_action('activate_git-up...') #4 {main} thrown in /var/www/vhosts/XXXXXXXXX.web3.alfahosting-server.de/httpdocs/XXXXXXXXX.XX/wp-content/plugins/git-updater-master/src/Git_Updater/Bootstrap.php on line 163

Regards
Mierscheid

**Comment by afragen** [comment]
Thanks for the report. I think I know what the issue is.
